// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 563915109;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__recipe__add_custom_ingredient_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "add_custom_ingredient",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_item = <crate::api::recipe::CustomIngredientDto>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::error::KimattaError>((move || {
                    let output_ok = crate::api::recipe::add_custom_ingredient(api_item)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__household__bootstrap_household_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "bootstrap_household",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::error::KimattaError>((move || {
                    let output_ok = crate::api::household::bootstrap_household()?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__health__core_version_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "core_version",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Ok::<_, ()>(crate::api::health::core_version())?;
                std::result::Result::Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__planning__ensure_planning_cycle_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ensure_planning_cycle",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_household_id = <String>::sse_decode(&mut deserializer);
            let api_default_anchor_date = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::error::KimattaError>((move || {
                    let output_ok = crate::api::planning::ensure_planning_cycle(
                        api_household_id,
                        api_default_anchor_date,
                    )?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__health__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Ok::<_, ()>({
                        crate::api::health::init_app();
                    })?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__recipe__list_custom_ingredients_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_custom_ingredients",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_household_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::error::KimattaError>((move || {
                    let output_ok = crate::api::recipe::list_custom_ingredients(api_household_id)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__recipe__list_recipes_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_recipes",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_household_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::error::KimattaError>((move || {
                    let output_ok = crate::api::recipe::list_recipes(api_household_id)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__recipe__load_recipe_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "load_recipe",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_household_id = <String>::sse_decode(&mut deserializer);
            let api_recipe_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::error::KimattaError>((move || {
                    let output_ok =
                        crate::api::recipe::load_recipe(api_household_id, api_recipe_id)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__health__open_database_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "open_database",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_db_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::error::KimattaError>((move || {
                    let output_ok = crate::api::health::open_database(api_db_path)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__household__rename_household_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "rename_household",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_household_id = <String>::sse_decode(&mut deserializer);
            let api_name = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::error::KimattaError>((move || {
                    let output_ok =
                        crate::api::household::rename_household(api_household_id, api_name)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__planning__save_planning_cycle_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "save_planning_cycle",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_household_id = <String>::sse_decode(&mut deserializer);
            let api_anchor_date = <String>::sse_decode(&mut deserializer);
            let api_length_days = <u32>::sse_decode(&mut deserializer);
            let api_meal_slots =
                <Vec<crate::api::planning::MealSlotDto>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::error::KimattaError>((move || {
                    let output_ok = crate::api::planning::save_planning_cycle(
                        api_household_id,
                        api_anchor_date,
                        api_length_days,
                        api_meal_slots,
                    )?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__recipe__save_recipe_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "save_recipe",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_recipe = <crate::api::recipe::RecipeDto>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::error::KimattaError>((move || {
                    let output_ok = crate::api::recipe::save_recipe(api_recipe)?;
                    std::result::Result::Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::recipe::CustomIngredientDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_householdId = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_storeCategory = <Option<String>>::sse_decode(deserializer);
        return crate::api::recipe::CustomIngredientDto {
            id: var_id,
            household_id: var_householdId,
            name: var_name,
            store_category: var_storeCategory,
        };
    }
}

impl SseDecode for crate::api::health::HealthReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_dbPath = <String>::sse_decode(deserializer);
        let mut var_schemaVersion = <u32>::sse_decode(deserializer);
        return crate::api::health::HealthReport {
            db_path: var_dbPath,
            schema_version: var_schemaVersion,
        };
    }
}

impl SseDecode for crate::api::household::HouseholdDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <Option<String>>::sse_decode(deserializer);
        let mut var_members = <Vec<crate::api::household::MemberDto>>::sse_decode(deserializer);
        return crate::api::household::HouseholdDto {
            id: var_id,
            name: var_name,
            members: var_members,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::recipe::IngredientLineDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_originalText = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_ingredient =
            <Option<crate::api::recipe::IngredientRefDto>>::sse_decode(deserializer);
        let mut var_quantity = <crate::api::recipe::QuantityDto>::sse_decode(deserializer);
        let mut var_unit = <crate::api::recipe::UnitDto>::sse_decode(deserializer);
        let mut var_preparation = <Option<String>>::sse_decode(deserializer);
        let mut var_optional = <bool>::sse_decode(deserializer);
        return crate::api::recipe::IngredientLineDto {
            original_text: var_originalText,
            name: var_name,
            ingredient: var_ingredient,
            quantity: var_quantity,
            unit: var_unit,
            preparation: var_preparation,
            optional: var_optional,
        };
    }
}

impl SseDecode for crate::api::recipe::IngredientRefDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_id = <String>::sse_decode(deserializer);
                return crate::api::recipe::IngredientRefDto::Catalog { id: var_id };
            }
            1 => {
                let mut var_id = <String>::sse_decode(deserializer);
                return crate::api::recipe::IngredientRefDto::Custom { id: var_id };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::error::KimattaError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::error::KimattaError::InvalidPath;
            }
            1 => {
                return crate::api::error::KimattaError::NotOpen;
            }
            2 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::error::KimattaError::Storage {
                    message: var_message,
                };
            }
            3 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::error::KimattaError::Planning {
                    message: var_message,
                };
            }
            4 => {
                let mut var_message = <String>::sse_decode(deserializer);
                return crate::api::error::KimattaError::Recipe {
                    message: var_message,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::recipe::CustomIngredientDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::recipe::CustomIngredientDto>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::recipe::IngredientLineDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::recipe::IngredientLineDto>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::planning::MealSlotDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::planning::MealSlotDto>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::household::MemberDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::household::MemberDto>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::recipe::RecipeSummaryDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::recipe::RecipeSummaryDto>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::planning::MealSlotDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::planning::MealSlotDto::Breakfast,
            1 => crate::api::planning::MealSlotDto::Lunch,
            2 => crate::api::planning::MealSlotDto::Dinner,
            _ => unreachable!("Invalid variant for MealSlotDto: {}", inner),
        };
    }
}

impl SseDecode for crate::api::household::MemberDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_displayName = <String>::sse_decode(deserializer);
        return crate::api::household::MemberDto {
            id: var_id,
            display_name: var_displayName,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::recipe::IngredientRefDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::recipe::IngredientRefDto>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::recipe::RecipeDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::recipe::RecipeDto>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::planning::PlanningCycleDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_householdId = <String>::sse_decode(deserializer);
        let mut var_anchorDate = <String>::sse_decode(deserializer);
        let mut var_lengthDays = <u32>::sse_decode(deserializer);
        let mut var_mealSlots = <Vec<crate::api::planning::MealSlotDto>>::sse_decode(deserializer);
        let mut var_dates = <Vec<String>>::sse_decode(deserializer);
        return crate::api::planning::PlanningCycleDto {
            household_id: var_householdId,
            anchor_date: var_anchorDate,
            length_days: var_lengthDays,
            meal_slots: var_mealSlots,
            dates: var_dates,
        };
    }
}

impl SseDecode for crate::api::recipe::QuantityDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::recipe::QuantityDto::Unknown;
            }
            1 => {
                let mut var_numer = <u32>::sse_decode(deserializer);
                let mut var_denom = <u32>::sse_decode(deserializer);
                return crate::api::recipe::QuantityDto::Exact {
                    numer: var_numer,
                    denom: var_denom,
                };
            }
            2 => {
                let mut var_minNumer = <u32>::sse_decode(deserializer);
                let mut var_minDenom = <u32>::sse_decode(deserializer);
                let mut var_maxNumer = <u32>::sse_decode(deserializer);
                let mut var_maxDenom = <u32>::sse_decode(deserializer);
                return crate::api::recipe::QuantityDto::Range {
                    min_numer: var_minNumer,
                    min_denom: var_minDenom,
                    max_numer: var_maxNumer,
                    max_denom: var_maxDenom,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::recipe::RecipeDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_householdId = <String>::sse_decode(deserializer);
        let mut var_title = <String>::sse_decode(deserializer);
        let mut var_servings = <Option<u32>>::sse_decode(deserializer);
        let mut var_instructions = <String>::sse_decode(deserializer);
        let mut var_lines = <Vec<crate::api::recipe::IngredientLineDto>>::sse_decode(deserializer);
        let mut var_provenance =
            <crate::api::recipe::RecipeProvenanceDto>::sse_decode(deserializer);
        return crate::api::recipe::RecipeDto {
            id: var_id,
            household_id: var_householdId,
            title: var_title,
            servings: var_servings,
            instructions: var_instructions,
            lines: var_lines,
            provenance: var_provenance,
        };
    }
}

impl SseDecode for crate::api::recipe::RecipeProvenanceDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_sourceUrl = <Option<String>>::sse_decode(deserializer);
        let mut var_sourceName = <Option<String>>::sse_decode(deserializer);
        let mut var_sourceAuthor = <Option<String>>::sse_decode(deserializer);
        return crate::api::recipe::RecipeProvenanceDto {
            kind: var_kind,
            source_url: var_sourceUrl,
            source_name: var_sourceName,
            source_author: var_sourceAuthor,
        };
    }
}

impl SseDecode for crate::api::recipe::RecipeSummaryDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_title = <String>::sse_decode(deserializer);
        return crate::api::recipe::RecipeSummaryDto {
            id: var_id,
            title: var_title,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::recipe::UnitDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::recipe::UnitDto::None;
            }
            1 => {
                let mut var_unit = <String>::sse_decode(deserializer);
                return crate::api::recipe::UnitDto::Known { unit: var_unit };
            }
            2 => {
                let mut var_text = <String>::sse_decode(deserializer);
                return crate::api::recipe::UnitDto::Other { text: var_text };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => {
            wire__crate__api__recipe__add_custom_ingredient_impl(port, ptr, rust_vec_len, data_len)
        }
        2 => {
            wire__crate__api__household__bootstrap_household_impl(port, ptr, rust_vec_len, data_len)
        }
        4 => wire__crate__api__planning__ensure_planning_cycle_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        5 => wire__crate__api__health__init_app_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__recipe__list_custom_ingredients_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        7 => wire__crate__api__recipe__list_recipes_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__recipe__load_recipe_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__health__open_database_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__household__rename_household_impl(port, ptr, rust_vec_len, data_len),
        11 => {
            wire__crate__api__planning__save_planning_cycle_impl(port, ptr, rust_vec_len, data_len)
        }
        12 => wire__crate__api__recipe__save_recipe_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        3 => wire__crate__api__health__core_version_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::recipe::CustomIngredientDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.household_id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.store_category.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::recipe::CustomIngredientDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::recipe::CustomIngredientDto>
    for crate::api::recipe::CustomIngredientDto
{
    fn into_into_dart(self) -> crate::api::recipe::CustomIngredientDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::health::HealthReport {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.db_path.into_into_dart().into_dart(),
            self.schema_version.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::health::HealthReport
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::health::HealthReport>
    for crate::api::health::HealthReport
{
    fn into_into_dart(self) -> crate::api::health::HealthReport {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::household::HouseholdDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.members.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::household::HouseholdDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::household::HouseholdDto>
    for crate::api::household::HouseholdDto
{
    fn into_into_dart(self) -> crate::api::household::HouseholdDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::recipe::IngredientLineDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.original_text.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.ingredient.into_into_dart().into_dart(),
            self.quantity.into_into_dart().into_dart(),
            self.unit.into_into_dart().into_dart(),
            self.preparation.into_into_dart().into_dart(),
            self.optional.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::recipe::IngredientLineDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::recipe::IngredientLineDto>
    for crate::api::recipe::IngredientLineDto
{
    fn into_into_dart(self) -> crate::api::recipe::IngredientLineDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::recipe::IngredientRefDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::recipe::IngredientRefDto::Catalog { id } => {
                [0.into_dart(), id.into_into_dart().into_dart()].into_dart()
            }
            crate::api::recipe::IngredientRefDto::Custom { id } => {
                [1.into_dart(), id.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::recipe::IngredientRefDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::recipe::IngredientRefDto>
    for crate::api::recipe::IngredientRefDto
{
    fn into_into_dart(self) -> crate::api::recipe::IngredientRefDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::error::KimattaError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::error::KimattaError::InvalidPath => [0.into_dart()].into_dart(),
            crate::api::error::KimattaError::NotOpen => [1.into_dart()].into_dart(),
            crate::api::error::KimattaError::Storage { message } => {
                [2.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::error::KimattaError::Planning { message } => {
                [3.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            crate::api::error::KimattaError::Recipe { message } => {
                [4.into_dart(), message.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::error::KimattaError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::error::KimattaError>
    for crate::api::error::KimattaError
{
    fn into_into_dart(self) -> crate::api::error::KimattaError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::planning::MealSlotDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Breakfast => 0.into_dart(),
            Self::Lunch => 1.into_dart(),
            Self::Dinner => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::planning::MealSlotDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::planning::MealSlotDto>
    for crate::api::planning::MealSlotDto
{
    fn into_into_dart(self) -> crate::api::planning::MealSlotDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::household::MemberDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.display_name.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::household::MemberDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::household::MemberDto>
    for crate::api::household::MemberDto
{
    fn into_into_dart(self) -> crate::api::household::MemberDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::planning::PlanningCycleDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.household_id.into_into_dart().into_dart(),
            self.anchor_date.into_into_dart().into_dart(),
            self.length_days.into_into_dart().into_dart(),
            self.meal_slots.into_into_dart().into_dart(),
            self.dates.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::planning::PlanningCycleDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::planning::PlanningCycleDto>
    for crate::api::planning::PlanningCycleDto
{
    fn into_into_dart(self) -> crate::api::planning::PlanningCycleDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::recipe::QuantityDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::recipe::QuantityDto::Unknown => [0.into_dart()].into_dart(),
            crate::api::recipe::QuantityDto::Exact { numer, denom } => [
                1.into_dart(),
                numer.into_into_dart().into_dart(),
                denom.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::recipe::QuantityDto::Range {
                min_numer,
                min_denom,
                max_numer,
                max_denom,
            } => [
                2.into_dart(),
                min_numer.into_into_dart().into_dart(),
                min_denom.into_into_dart().into_dart(),
                max_numer.into_into_dart().into_dart(),
                max_denom.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::recipe::QuantityDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::recipe::QuantityDto>
    for crate::api::recipe::QuantityDto
{
    fn into_into_dart(self) -> crate::api::recipe::QuantityDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::recipe::RecipeDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.household_id.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
            self.servings.into_into_dart().into_dart(),
            self.instructions.into_into_dart().into_dart(),
            self.lines.into_into_dart().into_dart(),
            self.provenance.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::recipe::RecipeDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::recipe::RecipeDto>
    for crate::api::recipe::RecipeDto
{
    fn into_into_dart(self) -> crate::api::recipe::RecipeDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::recipe::RecipeProvenanceDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.source_url.into_into_dart().into_dart(),
            self.source_name.into_into_dart().into_dart(),
            self.source_author.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::recipe::RecipeProvenanceDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::recipe::RecipeProvenanceDto>
    for crate::api::recipe::RecipeProvenanceDto
{
    fn into_into_dart(self) -> crate::api::recipe::RecipeProvenanceDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::recipe::RecipeSummaryDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::recipe::RecipeSummaryDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::recipe::RecipeSummaryDto>
    for crate::api::recipe::RecipeSummaryDto
{
    fn into_into_dart(self) -> crate::api::recipe::RecipeSummaryDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::recipe::UnitDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::recipe::UnitDto::None => [0.into_dart()].into_dart(),
            crate::api::recipe::UnitDto::Known { unit } => {
                [1.into_dart(), unit.into_into_dart().into_dart()].into_dart()
            }
            crate::api::recipe::UnitDto::Other { text } => {
                [2.into_dart(), text.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::recipe::UnitDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::recipe::UnitDto>
    for crate::api::recipe::UnitDto
{
    fn into_into_dart(self) -> crate::api::recipe::UnitDto {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::recipe::CustomIngredientDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.household_id, serializer);
        <String>::sse_encode(self.name, serializer);
        <Option<String>>::sse_encode(self.store_category, serializer);
    }
}

impl SseEncode for crate::api::health::HealthReport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.db_path, serializer);
        <u32>::sse_encode(self.schema_version, serializer);
    }
}

impl SseEncode for crate::api::household::HouseholdDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <Option<String>>::sse_encode(self.name, serializer);
        <Vec<crate::api::household::MemberDto>>::sse_encode(self.members, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::recipe::IngredientLineDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.original_text, serializer);
        <String>::sse_encode(self.name, serializer);
        <Option<crate::api::recipe::IngredientRefDto>>::sse_encode(self.ingredient, serializer);
        <crate::api::recipe::QuantityDto>::sse_encode(self.quantity, serializer);
        <crate::api::recipe::UnitDto>::sse_encode(self.unit, serializer);
        <Option<String>>::sse_encode(self.preparation, serializer);
        <bool>::sse_encode(self.optional, serializer);
    }
}

impl SseEncode for crate::api::recipe::IngredientRefDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::recipe::IngredientRefDto::Catalog { id } => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(id, serializer);
            }
            crate::api::recipe::IngredientRefDto::Custom { id } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(id, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::error::KimattaError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::error::KimattaError::InvalidPath => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::error::KimattaError::NotOpen => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::error::KimattaError::Storage { message } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::error::KimattaError::Planning { message } => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(message, serializer);
            }
            crate::api::error::KimattaError::Recipe { message } => {
                <i32>::sse_encode(4, serializer);
                <String>::sse_encode(message, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::recipe::CustomIngredientDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::recipe::CustomIngredientDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::recipe::IngredientLineDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::recipe::IngredientLineDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::planning::MealSlotDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::planning::MealSlotDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::household::MemberDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::household::MemberDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::recipe::RecipeSummaryDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::recipe::RecipeSummaryDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::planning::MealSlotDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::planning::MealSlotDto::Breakfast => 0,
                crate::api::planning::MealSlotDto::Lunch => 1,
                crate::api::planning::MealSlotDto::Dinner => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::household::MemberDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.display_name, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::recipe::IngredientRefDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::recipe::IngredientRefDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::recipe::RecipeDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::recipe::RecipeDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::planning::PlanningCycleDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.household_id, serializer);
        <String>::sse_encode(self.anchor_date, serializer);
        <u32>::sse_encode(self.length_days, serializer);
        <Vec<crate::api::planning::MealSlotDto>>::sse_encode(self.meal_slots, serializer);
        <Vec<String>>::sse_encode(self.dates, serializer);
    }
}

impl SseEncode for crate::api::recipe::QuantityDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::recipe::QuantityDto::Unknown => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::recipe::QuantityDto::Exact { numer, denom } => {
                <i32>::sse_encode(1, serializer);
                <u32>::sse_encode(numer, serializer);
                <u32>::sse_encode(denom, serializer);
            }
            crate::api::recipe::QuantityDto::Range {
                min_numer,
                min_denom,
                max_numer,
                max_denom,
            } => {
                <i32>::sse_encode(2, serializer);
                <u32>::sse_encode(min_numer, serializer);
                <u32>::sse_encode(min_denom, serializer);
                <u32>::sse_encode(max_numer, serializer);
                <u32>::sse_encode(max_denom, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::recipe::RecipeDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.household_id, serializer);
        <String>::sse_encode(self.title, serializer);
        <Option<u32>>::sse_encode(self.servings, serializer);
        <String>::sse_encode(self.instructions, serializer);
        <Vec<crate::api::recipe::IngredientLineDto>>::sse_encode(self.lines, serializer);
        <crate::api::recipe::RecipeProvenanceDto>::sse_encode(self.provenance, serializer);
    }
}

impl SseEncode for crate::api::recipe::RecipeProvenanceDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.kind, serializer);
        <Option<String>>::sse_encode(self.source_url, serializer);
        <Option<String>>::sse_encode(self.source_name, serializer);
        <Option<String>>::sse_encode(self.source_author, serializer);
    }
}

impl SseEncode for crate::api::recipe::RecipeSummaryDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.title, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::recipe::UnitDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::recipe::UnitDto::None => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::recipe::UnitDto::Known { unit } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(unit, serializer);
            }
            crate::api::recipe::UnitDto::Other { text } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(text, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.13.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
