// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/error.dart';
import 'api/health.dart';
import 'api/household.dart';
import 'api/planning.dart';
import 'api/recipe.dart';
import 'api/restrictions.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiHealthInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -878769591;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'kimatta_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<CustomIngredientDto> crateApiRecipeAddCustomIngredient({
    required CustomIngredientDto item,
  });

  Future<RecipeDto> crateApiRecipeArchiveRecipe({
    required String householdId,
    required String recipeId,
    required String archivedOn,
  });

  Future<HouseholdDto> crateApiHouseholdBootstrapHousehold();

  Future<HouseholdDto> crateApiHouseholdCompleteOnboarding({
    required String householdId,
  });

  String crateApiHealthCoreVersion();

  Future<PlanningCycleDto> crateApiPlanningEnsurePlanningCycle({
    required String householdId,
    required String defaultAnchorDate,
  });

  Future<void> crateApiHealthInitApp();

  Future<List<String>> crateApiRestrictionsKnownRestrictionKinds();

  Future<List<String>> crateApiRecipeKnownUnitKinds();

  Future<List<RecipeSummaryDto>> crateApiRecipeListArchivedRecipes({
    required String householdId,
  });

  Future<List<CustomIngredientDto>> crateApiRecipeListCustomIngredients({
    required String householdId,
  });

  Future<List<RecipeSummaryDto>> crateApiRecipeListRecipes({
    required String householdId,
  });

  Future<RecipeDto?> crateApiRecipeLoadRecipe({
    required String householdId,
    required String recipeId,
  });

  Future<List<RestrictionDto>> crateApiRestrictionsLoadRestrictions({
    required String householdId,
  });

  Future<HealthReport> crateApiHealthOpenDatabase({required String dbPath});

  Future<HouseholdDto> crateApiHouseholdRenameHousehold({
    required String householdId,
    String? name,
  });

  Future<RecipeDto> crateApiRecipeRestoreRecipe({
    required String householdId,
    required String recipeId,
  });

  Future<PlanningCycleDto> crateApiPlanningSavePlanningCycle({
    required String householdId,
    required String anchorDate,
    required int lengthDays,
    required List<MealSlotDto> mealSlots,
  });

  Future<RecipeDto> crateApiRecipeSaveRecipe({required RecipeDto recipe});

  Future<List<RestrictionDto>> crateApiRestrictionsSaveRestrictions({
    required String householdId,
    required List<RestrictionDto> restrictions,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<CustomIngredientDto> crateApiRecipeAddCustomIngredient({
    required CustomIngredientDto item,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_custom_ingredient_dto(item, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_custom_ingredient_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiRecipeAddCustomIngredientConstMeta,
        argValues: [item],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecipeAddCustomIngredientConstMeta =>
      const TaskConstMeta(
        debugName: "add_custom_ingredient",
        argNames: ["item"],
      );

  @override
  Future<RecipeDto> crateApiRecipeArchiveRecipe({
    required String householdId,
    required String recipeId,
    required String archivedOn,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(householdId, serializer);
          sse_encode_String(recipeId, serializer);
          sse_encode_String(archivedOn, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_recipe_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiRecipeArchiveRecipeConstMeta,
        argValues: [householdId, recipeId, archivedOn],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecipeArchiveRecipeConstMeta =>
      const TaskConstMeta(
        debugName: "archive_recipe",
        argNames: ["householdId", "recipeId", "archivedOn"],
      );

  @override
  Future<HouseholdDto> crateApiHouseholdBootstrapHousehold() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_household_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiHouseholdBootstrapHouseholdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHouseholdBootstrapHouseholdConstMeta =>
      const TaskConstMeta(debugName: "bootstrap_household", argNames: []);

  @override
  Future<HouseholdDto> crateApiHouseholdCompleteOnboarding({
    required String householdId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(householdId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_household_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiHouseholdCompleteOnboardingConstMeta,
        argValues: [householdId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHouseholdCompleteOnboardingConstMeta =>
      const TaskConstMeta(
        debugName: "complete_onboarding",
        argNames: ["householdId"],
      );

  @override
  String crateApiHealthCoreVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHealthCoreVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHealthCoreVersionConstMeta =>
      const TaskConstMeta(debugName: "core_version", argNames: []);

  @override
  Future<PlanningCycleDto> crateApiPlanningEnsurePlanningCycle({
    required String householdId,
    required String defaultAnchorDate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(householdId, serializer);
          sse_encode_String(defaultAnchorDate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_planning_cycle_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiPlanningEnsurePlanningCycleConstMeta,
        argValues: [householdId, defaultAnchorDate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlanningEnsurePlanningCycleConstMeta =>
      const TaskConstMeta(
        debugName: "ensure_planning_cycle",
        argNames: ["householdId", "defaultAnchorDate"],
      );

  @override
  Future<void> crateApiHealthInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHealthInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHealthInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<String>> crateApiRestrictionsKnownRestrictionKinds() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRestrictionsKnownRestrictionKindsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRestrictionsKnownRestrictionKindsConstMeta =>
      const TaskConstMeta(debugName: "known_restriction_kinds", argNames: []);

  @override
  Future<List<String>> crateApiRecipeKnownUnitKinds() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRecipeKnownUnitKindsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecipeKnownUnitKindsConstMeta =>
      const TaskConstMeta(debugName: "known_unit_kinds", argNames: []);

  @override
  Future<List<RecipeSummaryDto>> crateApiRecipeListArchivedRecipes({
    required String householdId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(householdId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_recipe_summary_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiRecipeListArchivedRecipesConstMeta,
        argValues: [householdId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecipeListArchivedRecipesConstMeta =>
      const TaskConstMeta(
        debugName: "list_archived_recipes",
        argNames: ["householdId"],
      );

  @override
  Future<List<CustomIngredientDto>> crateApiRecipeListCustomIngredients({
    required String householdId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(householdId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_custom_ingredient_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiRecipeListCustomIngredientsConstMeta,
        argValues: [householdId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecipeListCustomIngredientsConstMeta =>
      const TaskConstMeta(
        debugName: "list_custom_ingredients",
        argNames: ["householdId"],
      );

  @override
  Future<List<RecipeSummaryDto>> crateApiRecipeListRecipes({
    required String householdId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(householdId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_recipe_summary_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiRecipeListRecipesConstMeta,
        argValues: [householdId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecipeListRecipesConstMeta =>
      const TaskConstMeta(debugName: "list_recipes", argNames: ["householdId"]);

  @override
  Future<RecipeDto?> crateApiRecipeLoadRecipe({
    required String householdId,
    required String recipeId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(householdId, serializer);
          sse_encode_String(recipeId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_recipe_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiRecipeLoadRecipeConstMeta,
        argValues: [householdId, recipeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecipeLoadRecipeConstMeta => const TaskConstMeta(
    debugName: "load_recipe",
    argNames: ["householdId", "recipeId"],
  );

  @override
  Future<List<RestrictionDto>> crateApiRestrictionsLoadRestrictions({
    required String householdId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(householdId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_restriction_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiRestrictionsLoadRestrictionsConstMeta,
        argValues: [householdId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRestrictionsLoadRestrictionsConstMeta =>
      const TaskConstMeta(
        debugName: "load_restrictions",
        argNames: ["householdId"],
      );

  @override
  Future<HealthReport> crateApiHealthOpenDatabase({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_health_report,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiHealthOpenDatabaseConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHealthOpenDatabaseConstMeta =>
      const TaskConstMeta(debugName: "open_database", argNames: ["dbPath"]);

  @override
  Future<HouseholdDto> crateApiHouseholdRenameHousehold({
    required String householdId,
    String? name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(householdId, serializer);
          sse_encode_opt_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_household_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiHouseholdRenameHouseholdConstMeta,
        argValues: [householdId, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHouseholdRenameHouseholdConstMeta =>
      const TaskConstMeta(
        debugName: "rename_household",
        argNames: ["householdId", "name"],
      );

  @override
  Future<RecipeDto> crateApiRecipeRestoreRecipe({
    required String householdId,
    required String recipeId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(householdId, serializer);
          sse_encode_String(recipeId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_recipe_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiRecipeRestoreRecipeConstMeta,
        argValues: [householdId, recipeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecipeRestoreRecipeConstMeta =>
      const TaskConstMeta(
        debugName: "restore_recipe",
        argNames: ["householdId", "recipeId"],
      );

  @override
  Future<PlanningCycleDto> crateApiPlanningSavePlanningCycle({
    required String householdId,
    required String anchorDate,
    required int lengthDays,
    required List<MealSlotDto> mealSlots,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(householdId, serializer);
          sse_encode_String(anchorDate, serializer);
          sse_encode_u_32(lengthDays, serializer);
          sse_encode_list_meal_slot_dto(mealSlots, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_planning_cycle_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiPlanningSavePlanningCycleConstMeta,
        argValues: [householdId, anchorDate, lengthDays, mealSlots],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlanningSavePlanningCycleConstMeta =>
      const TaskConstMeta(
        debugName: "save_planning_cycle",
        argNames: ["householdId", "anchorDate", "lengthDays", "mealSlots"],
      );

  @override
  Future<RecipeDto> crateApiRecipeSaveRecipe({required RecipeDto recipe}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_recipe_dto(recipe, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_recipe_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiRecipeSaveRecipeConstMeta,
        argValues: [recipe],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecipeSaveRecipeConstMeta =>
      const TaskConstMeta(debugName: "save_recipe", argNames: ["recipe"]);

  @override
  Future<List<RestrictionDto>> crateApiRestrictionsSaveRestrictions({
    required String householdId,
    required List<RestrictionDto> restrictions,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(householdId, serializer);
          sse_encode_list_restriction_dto(restrictions, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_restriction_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiRestrictionsSaveRestrictionsConstMeta,
        argValues: [householdId, restrictions],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRestrictionsSaveRestrictionsConstMeta =>
      const TaskConstMeta(
        debugName: "save_restrictions",
        argNames: ["householdId", "restrictions"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CustomIngredientDto dco_decode_box_autoadd_custom_ingredient_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_custom_ingredient_dto(raw);
  }

  @protected
  IngredientRefDto dco_decode_box_autoadd_ingredient_ref_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ingredient_ref_dto(raw);
  }

  @protected
  RecipeDto dco_decode_box_autoadd_recipe_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_recipe_dto(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CustomIngredientDto dco_decode_custom_ingredient_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CustomIngredientDto(
      id: dco_decode_String(arr[0]),
      householdId: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
      storeCategory: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  HealthReport dco_decode_health_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HealthReport(
      dbPath: dco_decode_String(arr[0]),
      schemaVersion: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  HouseholdDto dco_decode_household_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return HouseholdDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      members: dco_decode_list_member_dto(arr[2]),
      onboarded: dco_decode_bool(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  IngredientLineDto dco_decode_ingredient_line_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return IngredientLineDto(
      originalText: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      ingredient: dco_decode_opt_box_autoadd_ingredient_ref_dto(arr[2]),
      quantity: dco_decode_quantity_dto(arr[3]),
      unit: dco_decode_unit_dto(arr[4]),
      preparation: dco_decode_opt_String(arr[5]),
      optional: dco_decode_bool(arr[6]),
    );
  }

  @protected
  IngredientRefDto dco_decode_ingredient_ref_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return IngredientRefDto_Catalog(id: dco_decode_String(raw[1]));
      case 1:
        return IngredientRefDto_Custom(id: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  KimattaError dco_decode_kimatta_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return KimattaError_InvalidPath();
      case 1:
        return KimattaError_NotOpen();
      case 2:
        return KimattaError_Storage(message: dco_decode_String(raw[1]));
      case 3:
        return KimattaError_Planning(message: dco_decode_String(raw[1]));
      case 4:
        return KimattaError_Recipe(message: dco_decode_String(raw[1]));
      case 5:
        return KimattaError_Restriction(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CustomIngredientDto> dco_decode_list_custom_ingredient_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_custom_ingredient_dto)
        .toList();
  }

  @protected
  List<IngredientLineDto> dco_decode_list_ingredient_line_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ingredient_line_dto).toList();
  }

  @protected
  List<MealSlotDto> dco_decode_list_meal_slot_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_meal_slot_dto).toList();
  }

  @protected
  List<MemberDto> dco_decode_list_member_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_member_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RecipeSummaryDto> dco_decode_list_recipe_summary_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_recipe_summary_dto).toList();
  }

  @protected
  List<RestrictionDto> dco_decode_list_restriction_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_restriction_dto).toList();
  }

  @protected
  MealSlotDto dco_decode_meal_slot_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MealSlotDto.values[raw as int];
  }

  @protected
  MemberDto dco_decode_member_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MemberDto(
      id: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  IngredientRefDto? dco_decode_opt_box_autoadd_ingredient_ref_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_ingredient_ref_dto(raw);
  }

  @protected
  RecipeDto? dco_decode_opt_box_autoadd_recipe_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_recipe_dto(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  PlanningCycleDto dco_decode_planning_cycle_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PlanningCycleDto(
      householdId: dco_decode_String(arr[0]),
      anchorDate: dco_decode_String(arr[1]),
      lengthDays: dco_decode_u_32(arr[2]),
      mealSlots: dco_decode_list_meal_slot_dto(arr[3]),
      dates: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  QuantityDto dco_decode_quantity_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return QuantityDto_Unknown();
      case 1:
        return QuantityDto_Exact(
          numer: dco_decode_u_32(raw[1]),
          denom: dco_decode_u_32(raw[2]),
        );
      case 2:
        return QuantityDto_Range(
          minNumer: dco_decode_u_32(raw[1]),
          minDenom: dco_decode_u_32(raw[2]),
          maxNumer: dco_decode_u_32(raw[3]),
          maxDenom: dco_decode_u_32(raw[4]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  RecipeDto dco_decode_recipe_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return RecipeDto(
      id: dco_decode_String(arr[0]),
      householdId: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      servings: dco_decode_opt_box_autoadd_u_32(arr[3]),
      instructions: dco_decode_String(arr[4]),
      lines: dco_decode_list_ingredient_line_dto(arr[5]),
      provenance: dco_decode_recipe_provenance_dto(arr[6]),
      archivedAt: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  RecipeProvenanceDto dco_decode_recipe_provenance_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RecipeProvenanceDto(
      kind: dco_decode_String(arr[0]),
      sourceUrl: dco_decode_opt_String(arr[1]),
      sourceName: dco_decode_opt_String(arr[2]),
      sourceAuthor: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  RecipeSummaryDto dco_decode_recipe_summary_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RecipeSummaryDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
    );
  }

  @protected
  RestrictionDto dco_decode_restriction_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return RestrictionDto_Known(kind: dco_decode_String(raw[1]));
      case 1:
        return RestrictionDto_Other(text: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UnitDto dco_decode_unit_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return UnitDto_None();
      case 1:
        return UnitDto_Known(unit: dco_decode_String(raw[1]));
      case 2:
        return UnitDto_Other(text: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CustomIngredientDto sse_decode_box_autoadd_custom_ingredient_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_custom_ingredient_dto(deserializer));
  }

  @protected
  IngredientRefDto sse_decode_box_autoadd_ingredient_ref_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ingredient_ref_dto(deserializer));
  }

  @protected
  RecipeDto sse_decode_box_autoadd_recipe_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_recipe_dto(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CustomIngredientDto sse_decode_custom_ingredient_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_householdId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_storeCategory = sse_decode_opt_String(deserializer);
    return CustomIngredientDto(
      id: var_id,
      householdId: var_householdId,
      name: var_name,
      storeCategory: var_storeCategory,
    );
  }

  @protected
  HealthReport sse_decode_health_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dbPath = sse_decode_String(deserializer);
    var var_schemaVersion = sse_decode_u_32(deserializer);
    return HealthReport(dbPath: var_dbPath, schemaVersion: var_schemaVersion);
  }

  @protected
  HouseholdDto sse_decode_household_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_members = sse_decode_list_member_dto(deserializer);
    var var_onboarded = sse_decode_bool(deserializer);
    return HouseholdDto(
      id: var_id,
      name: var_name,
      members: var_members,
      onboarded: var_onboarded,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  IngredientLineDto sse_decode_ingredient_line_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_originalText = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_ingredient = sse_decode_opt_box_autoadd_ingredient_ref_dto(
      deserializer,
    );
    var var_quantity = sse_decode_quantity_dto(deserializer);
    var var_unit = sse_decode_unit_dto(deserializer);
    var var_preparation = sse_decode_opt_String(deserializer);
    var var_optional = sse_decode_bool(deserializer);
    return IngredientLineDto(
      originalText: var_originalText,
      name: var_name,
      ingredient: var_ingredient,
      quantity: var_quantity,
      unit: var_unit,
      preparation: var_preparation,
      optional: var_optional,
    );
  }

  @protected
  IngredientRefDto sse_decode_ingredient_ref_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_id = sse_decode_String(deserializer);
        return IngredientRefDto_Catalog(id: var_id);
      case 1:
        var var_id = sse_decode_String(deserializer);
        return IngredientRefDto_Custom(id: var_id);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  KimattaError sse_decode_kimatta_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return KimattaError_InvalidPath();
      case 1:
        return KimattaError_NotOpen();
      case 2:
        var var_message = sse_decode_String(deserializer);
        return KimattaError_Storage(message: var_message);
      case 3:
        var var_message = sse_decode_String(deserializer);
        return KimattaError_Planning(message: var_message);
      case 4:
        var var_message = sse_decode_String(deserializer);
        return KimattaError_Recipe(message: var_message);
      case 5:
        var var_message = sse_decode_String(deserializer);
        return KimattaError_Restriction(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CustomIngredientDto> sse_decode_list_custom_ingredient_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CustomIngredientDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_custom_ingredient_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<IngredientLineDto> sse_decode_list_ingredient_line_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <IngredientLineDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ingredient_line_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<MealSlotDto> sse_decode_list_meal_slot_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MealSlotDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_meal_slot_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<MemberDto> sse_decode_list_member_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MemberDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_member_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RecipeSummaryDto> sse_decode_list_recipe_summary_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RecipeSummaryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_recipe_summary_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<RestrictionDto> sse_decode_list_restriction_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RestrictionDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_restriction_dto(deserializer));
    }
    return ans_;
  }

  @protected
  MealSlotDto sse_decode_meal_slot_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MealSlotDto.values[inner];
  }

  @protected
  MemberDto sse_decode_member_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    return MemberDto(id: var_id, displayName: var_displayName);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  IngredientRefDto? sse_decode_opt_box_autoadd_ingredient_ref_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_ingredient_ref_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RecipeDto? sse_decode_opt_box_autoadd_recipe_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_recipe_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlanningCycleDto sse_decode_planning_cycle_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_householdId = sse_decode_String(deserializer);
    var var_anchorDate = sse_decode_String(deserializer);
    var var_lengthDays = sse_decode_u_32(deserializer);
    var var_mealSlots = sse_decode_list_meal_slot_dto(deserializer);
    var var_dates = sse_decode_list_String(deserializer);
    return PlanningCycleDto(
      householdId: var_householdId,
      anchorDate: var_anchorDate,
      lengthDays: var_lengthDays,
      mealSlots: var_mealSlots,
      dates: var_dates,
    );
  }

  @protected
  QuantityDto sse_decode_quantity_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return QuantityDto_Unknown();
      case 1:
        var var_numer = sse_decode_u_32(deserializer);
        var var_denom = sse_decode_u_32(deserializer);
        return QuantityDto_Exact(numer: var_numer, denom: var_denom);
      case 2:
        var var_minNumer = sse_decode_u_32(deserializer);
        var var_minDenom = sse_decode_u_32(deserializer);
        var var_maxNumer = sse_decode_u_32(deserializer);
        var var_maxDenom = sse_decode_u_32(deserializer);
        return QuantityDto_Range(
          minNumer: var_minNumer,
          minDenom: var_minDenom,
          maxNumer: var_maxNumer,
          maxDenom: var_maxDenom,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  RecipeDto sse_decode_recipe_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_householdId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_servings = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_instructions = sse_decode_String(deserializer);
    var var_lines = sse_decode_list_ingredient_line_dto(deserializer);
    var var_provenance = sse_decode_recipe_provenance_dto(deserializer);
    var var_archivedAt = sse_decode_opt_String(deserializer);
    return RecipeDto(
      id: var_id,
      householdId: var_householdId,
      title: var_title,
      servings: var_servings,
      instructions: var_instructions,
      lines: var_lines,
      provenance: var_provenance,
      archivedAt: var_archivedAt,
    );
  }

  @protected
  RecipeProvenanceDto sse_decode_recipe_provenance_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_sourceUrl = sse_decode_opt_String(deserializer);
    var var_sourceName = sse_decode_opt_String(deserializer);
    var var_sourceAuthor = sse_decode_opt_String(deserializer);
    return RecipeProvenanceDto(
      kind: var_kind,
      sourceUrl: var_sourceUrl,
      sourceName: var_sourceName,
      sourceAuthor: var_sourceAuthor,
    );
  }

  @protected
  RecipeSummaryDto sse_decode_recipe_summary_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    return RecipeSummaryDto(id: var_id, title: var_title);
  }

  @protected
  RestrictionDto sse_decode_restriction_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_kind = sse_decode_String(deserializer);
        return RestrictionDto_Known(kind: var_kind);
      case 1:
        var var_text = sse_decode_String(deserializer);
        return RestrictionDto_Other(text: var_text);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UnitDto sse_decode_unit_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return UnitDto_None();
      case 1:
        var var_unit = sse_decode_String(deserializer);
        return UnitDto_Known(unit: var_unit);
      case 2:
        var var_text = sse_decode_String(deserializer);
        return UnitDto_Other(text: var_text);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_custom_ingredient_dto(
    CustomIngredientDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_custom_ingredient_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ingredient_ref_dto(
    IngredientRefDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ingredient_ref_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_recipe_dto(
    RecipeDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_recipe_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_custom_ingredient_dto(
    CustomIngredientDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.householdId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.storeCategory, serializer);
  }

  @protected
  void sse_encode_health_report(HealthReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.dbPath, serializer);
    sse_encode_u_32(self.schemaVersion, serializer);
  }

  @protected
  void sse_encode_household_dto(HouseholdDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_list_member_dto(self.members, serializer);
    sse_encode_bool(self.onboarded, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_ingredient_line_dto(
    IngredientLineDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.originalText, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_box_autoadd_ingredient_ref_dto(self.ingredient, serializer);
    sse_encode_quantity_dto(self.quantity, serializer);
    sse_encode_unit_dto(self.unit, serializer);
    sse_encode_opt_String(self.preparation, serializer);
    sse_encode_bool(self.optional, serializer);
  }

  @protected
  void sse_encode_ingredient_ref_dto(
    IngredientRefDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case IngredientRefDto_Catalog(id: final id):
        sse_encode_i_32(0, serializer);
        sse_encode_String(id, serializer);
      case IngredientRefDto_Custom(id: final id):
        sse_encode_i_32(1, serializer);
        sse_encode_String(id, serializer);
    }
  }

  @protected
  void sse_encode_kimatta_error(KimattaError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case KimattaError_InvalidPath():
        sse_encode_i_32(0, serializer);
      case KimattaError_NotOpen():
        sse_encode_i_32(1, serializer);
      case KimattaError_Storage(message: final message):
        sse_encode_i_32(2, serializer);
        sse_encode_String(message, serializer);
      case KimattaError_Planning(message: final message):
        sse_encode_i_32(3, serializer);
        sse_encode_String(message, serializer);
      case KimattaError_Recipe(message: final message):
        sse_encode_i_32(4, serializer);
        sse_encode_String(message, serializer);
      case KimattaError_Restriction(message: final message):
        sse_encode_i_32(5, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_custom_ingredient_dto(
    List<CustomIngredientDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_custom_ingredient_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ingredient_line_dto(
    List<IngredientLineDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ingredient_line_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_meal_slot_dto(
    List<MealSlotDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_meal_slot_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_member_dto(
    List<MemberDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_member_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_recipe_summary_dto(
    List<RecipeSummaryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_recipe_summary_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_restriction_dto(
    List<RestrictionDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_restriction_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_meal_slot_dto(MealSlotDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_member_dto(MemberDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.displayName, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_ingredient_ref_dto(
    IngredientRefDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_ingredient_ref_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_recipe_dto(
    RecipeDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_recipe_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_planning_cycle_dto(
    PlanningCycleDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.householdId, serializer);
    sse_encode_String(self.anchorDate, serializer);
    sse_encode_u_32(self.lengthDays, serializer);
    sse_encode_list_meal_slot_dto(self.mealSlots, serializer);
    sse_encode_list_String(self.dates, serializer);
  }

  @protected
  void sse_encode_quantity_dto(QuantityDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case QuantityDto_Unknown():
        sse_encode_i_32(0, serializer);
      case QuantityDto_Exact(numer: final numer, denom: final denom):
        sse_encode_i_32(1, serializer);
        sse_encode_u_32(numer, serializer);
        sse_encode_u_32(denom, serializer);
      case QuantityDto_Range(
        minNumer: final minNumer,
        minDenom: final minDenom,
        maxNumer: final maxNumer,
        maxDenom: final maxDenom,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_u_32(minNumer, serializer);
        sse_encode_u_32(minDenom, serializer);
        sse_encode_u_32(maxNumer, serializer);
        sse_encode_u_32(maxDenom, serializer);
    }
  }

  @protected
  void sse_encode_recipe_dto(RecipeDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.householdId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_box_autoadd_u_32(self.servings, serializer);
    sse_encode_String(self.instructions, serializer);
    sse_encode_list_ingredient_line_dto(self.lines, serializer);
    sse_encode_recipe_provenance_dto(self.provenance, serializer);
    sse_encode_opt_String(self.archivedAt, serializer);
  }

  @protected
  void sse_encode_recipe_provenance_dto(
    RecipeProvenanceDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.sourceUrl, serializer);
    sse_encode_opt_String(self.sourceName, serializer);
    sse_encode_opt_String(self.sourceAuthor, serializer);
  }

  @protected
  void sse_encode_recipe_summary_dto(
    RecipeSummaryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
  }

  @protected
  void sse_encode_restriction_dto(
    RestrictionDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case RestrictionDto_Known(kind: final kind):
        sse_encode_i_32(0, serializer);
        sse_encode_String(kind, serializer);
      case RestrictionDto_Other(text: final text):
        sse_encode_i_32(1, serializer);
        sse_encode_String(text, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_unit_dto(UnitDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case UnitDto_None():
        sse_encode_i_32(0, serializer);
      case UnitDto_Known(unit: final unit):
        sse_encode_i_32(1, serializer);
        sse_encode_String(unit, serializer);
      case UnitDto_Other(text: final text):
        sse_encode_i_32(2, serializer);
        sse_encode_String(text, serializer);
    }
  }
}
