// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/error.dart';
import 'api/health.dart';
import 'api/household.dart';
import 'api/planning.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  HealthReport dco_decode_health_report(dynamic raw);

  @protected
  HouseholdDto dco_decode_household_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  KimattaError dco_decode_kimatta_error(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<MealSlotDto> dco_decode_list_meal_slot_dto(dynamic raw);

  @protected
  List<MemberDto> dco_decode_list_member_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MealSlotDto dco_decode_meal_slot_dto(dynamic raw);

  @protected
  MemberDto dco_decode_member_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlanningCycleDto dco_decode_planning_cycle_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  HealthReport sse_decode_health_report(SseDeserializer deserializer);

  @protected
  HouseholdDto sse_decode_household_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  KimattaError sse_decode_kimatta_error(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<MealSlotDto> sse_decode_list_meal_slot_dto(SseDeserializer deserializer);

  @protected
  List<MemberDto> sse_decode_list_member_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MealSlotDto sse_decode_meal_slot_dto(SseDeserializer deserializer);

  @protected
  MemberDto sse_decode_member_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlanningCycleDto sse_decode_planning_cycle_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_health_report(HealthReport self, SseSerializer serializer);

  @protected
  void sse_encode_household_dto(HouseholdDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_kimatta_error(KimattaError self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_meal_slot_dto(
    List<MealSlotDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_member_dto(
    List<MemberDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meal_slot_dto(MealSlotDto self, SseSerializer serializer);

  @protected
  void sse_encode_member_dto(MemberDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_planning_cycle_dto(
    PlanningCycleDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
