// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/error.dart';
import 'api/health.dart';
import 'api/household.dart';
import 'api/planned_meals.dart';
import 'api/planning.dart';
import 'api/recipe.dart';
import 'api/restrictions.dart';
import 'api/starter.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CustomIngredientDto dco_decode_box_autoadd_custom_ingredient_dto(dynamic raw);

  @protected
  IngredientRefDto dco_decode_box_autoadd_ingredient_ref_dto(dynamic raw);

  @protected
  PlannedMealDto dco_decode_box_autoadd_planned_meal_dto(dynamic raw);

  @protected
  RecipeDto dco_decode_box_autoadd_recipe_dto(dynamic raw);

  @protected
  RestrictionAssessmentDto dco_decode_box_autoadd_restriction_assessment_dto(
    dynamic raw,
  );

  @protected
  ScaleDto dco_decode_box_autoadd_scale_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  ConflictDto dco_decode_conflict_dto(dynamic raw);

  @protected
  CustomIngredientDto dco_decode_custom_ingredient_dto(dynamic raw);

  @protected
  HealthReport dco_decode_health_report(dynamic raw);

  @protected
  HouseholdDto dco_decode_household_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  IngredientLineDto dco_decode_ingredient_line_dto(dynamic raw);

  @protected
  IngredientRefDto dco_decode_ingredient_ref_dto(dynamic raw);

  @protected
  KimattaError dco_decode_kimatta_error(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ConflictDto> dco_decode_list_conflict_dto(dynamic raw);

  @protected
  List<CustomIngredientDto> dco_decode_list_custom_ingredient_dto(dynamic raw);

  @protected
  List<IngredientLineDto> dco_decode_list_ingredient_line_dto(dynamic raw);

  @protected
  List<MealComponentDto> dco_decode_list_meal_component_dto(dynamic raw);

  @protected
  List<MealSlotDto> dco_decode_list_meal_slot_dto(dynamic raw);

  @protected
  List<MemberDto> dco_decode_list_member_dto(dynamic raw);

  @protected
  List<PlannedMealDto> dco_decode_list_planned_meal_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RecipeSummaryDto> dco_decode_list_recipe_summary_dto(dynamic raw);

  @protected
  List<RestrictionDto> dco_decode_list_restriction_dto(dynamic raw);

  @protected
  MealComponentDto dco_decode_meal_component_dto(dynamic raw);

  @protected
  MealSlotDto dco_decode_meal_slot_dto(dynamic raw);

  @protected
  MemberDto dco_decode_member_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  IngredientRefDto? dco_decode_opt_box_autoadd_ingredient_ref_dto(dynamic raw);

  @protected
  PlannedMealDto? dco_decode_opt_box_autoadd_planned_meal_dto(dynamic raw);

  @protected
  RecipeDto? dco_decode_opt_box_autoadd_recipe_dto(dynamic raw);

  @protected
  RestrictionAssessmentDto?
  dco_decode_opt_box_autoadd_restriction_assessment_dto(dynamic raw);

  @protected
  ScaleDto? dco_decode_opt_box_autoadd_scale_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PlannedMealDto dco_decode_planned_meal_dto(dynamic raw);

  @protected
  PlanningCycleDto dco_decode_planning_cycle_dto(dynamic raw);

  @protected
  QuantityDto dco_decode_quantity_dto(dynamic raw);

  @protected
  RecipeDto dco_decode_recipe_dto(dynamic raw);

  @protected
  RecipeProvenanceDto dco_decode_recipe_provenance_dto(dynamic raw);

  @protected
  RecipeSummaryDto dco_decode_recipe_summary_dto(dynamic raw);

  @protected
  RestrictionAssessmentDto dco_decode_restriction_assessment_dto(dynamic raw);

  @protected
  RestrictionDto dco_decode_restriction_dto(dynamic raw);

  @protected
  ScaleDto dco_decode_scale_dto(dynamic raw);

  @protected
  StarterInstallReportDto dco_decode_starter_install_report_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UnitDto dco_decode_unit_dto(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CustomIngredientDto sse_decode_box_autoadd_custom_ingredient_dto(
    SseDeserializer deserializer,
  );

  @protected
  IngredientRefDto sse_decode_box_autoadd_ingredient_ref_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlannedMealDto sse_decode_box_autoadd_planned_meal_dto(
    SseDeserializer deserializer,
  );

  @protected
  RecipeDto sse_decode_box_autoadd_recipe_dto(SseDeserializer deserializer);

  @protected
  RestrictionAssessmentDto sse_decode_box_autoadd_restriction_assessment_dto(
    SseDeserializer deserializer,
  );

  @protected
  ScaleDto sse_decode_box_autoadd_scale_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ConflictDto sse_decode_conflict_dto(SseDeserializer deserializer);

  @protected
  CustomIngredientDto sse_decode_custom_ingredient_dto(
    SseDeserializer deserializer,
  );

  @protected
  HealthReport sse_decode_health_report(SseDeserializer deserializer);

  @protected
  HouseholdDto sse_decode_household_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  IngredientLineDto sse_decode_ingredient_line_dto(
    SseDeserializer deserializer,
  );

  @protected
  IngredientRefDto sse_decode_ingredient_ref_dto(SseDeserializer deserializer);

  @protected
  KimattaError sse_decode_kimatta_error(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ConflictDto> sse_decode_list_conflict_dto(SseDeserializer deserializer);

  @protected
  List<CustomIngredientDto> sse_decode_list_custom_ingredient_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<IngredientLineDto> sse_decode_list_ingredient_line_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<MealComponentDto> sse_decode_list_meal_component_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<MealSlotDto> sse_decode_list_meal_slot_dto(SseDeserializer deserializer);

  @protected
  List<MemberDto> sse_decode_list_member_dto(SseDeserializer deserializer);

  @protected
  List<PlannedMealDto> sse_decode_list_planned_meal_dto(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RecipeSummaryDto> sse_decode_list_recipe_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<RestrictionDto> sse_decode_list_restriction_dto(
    SseDeserializer deserializer,
  );

  @protected
  MealComponentDto sse_decode_meal_component_dto(SseDeserializer deserializer);

  @protected
  MealSlotDto sse_decode_meal_slot_dto(SseDeserializer deserializer);

  @protected
  MemberDto sse_decode_member_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  IngredientRefDto? sse_decode_opt_box_autoadd_ingredient_ref_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlannedMealDto? sse_decode_opt_box_autoadd_planned_meal_dto(
    SseDeserializer deserializer,
  );

  @protected
  RecipeDto? sse_decode_opt_box_autoadd_recipe_dto(
    SseDeserializer deserializer,
  );

  @protected
  RestrictionAssessmentDto?
  sse_decode_opt_box_autoadd_restriction_assessment_dto(
    SseDeserializer deserializer,
  );

  @protected
  ScaleDto? sse_decode_opt_box_autoadd_scale_dto(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PlannedMealDto sse_decode_planned_meal_dto(SseDeserializer deserializer);

  @protected
  PlanningCycleDto sse_decode_planning_cycle_dto(SseDeserializer deserializer);

  @protected
  QuantityDto sse_decode_quantity_dto(SseDeserializer deserializer);

  @protected
  RecipeDto sse_decode_recipe_dto(SseDeserializer deserializer);

  @protected
  RecipeProvenanceDto sse_decode_recipe_provenance_dto(
    SseDeserializer deserializer,
  );

  @protected
  RecipeSummaryDto sse_decode_recipe_summary_dto(SseDeserializer deserializer);

  @protected
  RestrictionAssessmentDto sse_decode_restriction_assessment_dto(
    SseDeserializer deserializer,
  );

  @protected
  RestrictionDto sse_decode_restriction_dto(SseDeserializer deserializer);

  @protected
  ScaleDto sse_decode_scale_dto(SseDeserializer deserializer);

  @protected
  StarterInstallReportDto sse_decode_starter_install_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UnitDto sse_decode_unit_dto(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_custom_ingredient_dto(
    CustomIngredientDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ingredient_ref_dto(
    IngredientRefDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_planned_meal_dto(
    PlannedMealDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_recipe_dto(
    RecipeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_restriction_assessment_dto(
    RestrictionAssessmentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_scale_dto(
    ScaleDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_dto(ConflictDto self, SseSerializer serializer);

  @protected
  void sse_encode_custom_ingredient_dto(
    CustomIngredientDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_health_report(HealthReport self, SseSerializer serializer);

  @protected
  void sse_encode_household_dto(HouseholdDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_ingredient_line_dto(
    IngredientLineDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ingredient_ref_dto(
    IngredientRefDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_kimatta_error(KimattaError self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_conflict_dto(
    List<ConflictDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_custom_ingredient_dto(
    List<CustomIngredientDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ingredient_line_dto(
    List<IngredientLineDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_meal_component_dto(
    List<MealComponentDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_meal_slot_dto(
    List<MealSlotDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_member_dto(
    List<MemberDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_planned_meal_dto(
    List<PlannedMealDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_recipe_summary_dto(
    List<RecipeSummaryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_restriction_dto(
    List<RestrictionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meal_component_dto(
    MealComponentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meal_slot_dto(MealSlotDto self, SseSerializer serializer);

  @protected
  void sse_encode_member_dto(MemberDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ingredient_ref_dto(
    IngredientRefDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_planned_meal_dto(
    PlannedMealDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_recipe_dto(
    RecipeDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_restriction_assessment_dto(
    RestrictionAssessmentDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_scale_dto(
    ScaleDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_planned_meal_dto(
    PlannedMealDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_planning_cycle_dto(
    PlanningCycleDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_quantity_dto(QuantityDto self, SseSerializer serializer);

  @protected
  void sse_encode_recipe_dto(RecipeDto self, SseSerializer serializer);

  @protected
  void sse_encode_recipe_provenance_dto(
    RecipeProvenanceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recipe_summary_dto(
    RecipeSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_restriction_assessment_dto(
    RestrictionAssessmentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_restriction_dto(
    RestrictionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scale_dto(ScaleDto self, SseSerializer serializer);

  @protected
  void sse_encode_starter_install_report_dto(
    StarterInstallReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_unit_dto(UnitDto self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
