// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/error.dart';
import 'api/health.dart';
import 'api/household.dart';
import 'api/planning.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiHealthInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1168370520;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'kimatta_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<HouseholdDto> crateApiHouseholdBootstrapHousehold();

  String crateApiHealthCoreVersion();

  Future<PlanningCycleDto> crateApiPlanningEnsurePlanningCycle({
    required String householdId,
    required String defaultAnchorDate,
  });

  Future<void> crateApiHealthInitApp();

  Future<HealthReport> crateApiHealthOpenDatabase({required String dbPath});

  Future<HouseholdDto> crateApiHouseholdRenameHousehold({
    required String householdId,
    String? name,
  });

  Future<PlanningCycleDto> crateApiPlanningSavePlanningCycle({
    required String householdId,
    required String anchorDate,
    required int lengthDays,
    required List<MealSlotDto> mealSlots,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<HouseholdDto> crateApiHouseholdBootstrapHousehold() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_household_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiHouseholdBootstrapHouseholdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHouseholdBootstrapHouseholdConstMeta =>
      const TaskConstMeta(debugName: "bootstrap_household", argNames: []);

  @override
  String crateApiHealthCoreVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHealthCoreVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHealthCoreVersionConstMeta =>
      const TaskConstMeta(debugName: "core_version", argNames: []);

  @override
  Future<PlanningCycleDto> crateApiPlanningEnsurePlanningCycle({
    required String householdId,
    required String defaultAnchorDate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(householdId, serializer);
          sse_encode_String(defaultAnchorDate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_planning_cycle_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiPlanningEnsurePlanningCycleConstMeta,
        argValues: [householdId, defaultAnchorDate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlanningEnsurePlanningCycleConstMeta =>
      const TaskConstMeta(
        debugName: "ensure_planning_cycle",
        argNames: ["householdId", "defaultAnchorDate"],
      );

  @override
  Future<void> crateApiHealthInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHealthInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHealthInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<HealthReport> crateApiHealthOpenDatabase({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_health_report,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiHealthOpenDatabaseConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHealthOpenDatabaseConstMeta =>
      const TaskConstMeta(debugName: "open_database", argNames: ["dbPath"]);

  @override
  Future<HouseholdDto> crateApiHouseholdRenameHousehold({
    required String householdId,
    String? name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(householdId, serializer);
          sse_encode_opt_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_household_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiHouseholdRenameHouseholdConstMeta,
        argValues: [householdId, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHouseholdRenameHouseholdConstMeta =>
      const TaskConstMeta(
        debugName: "rename_household",
        argNames: ["householdId", "name"],
      );

  @override
  Future<PlanningCycleDto> crateApiPlanningSavePlanningCycle({
    required String householdId,
    required String anchorDate,
    required int lengthDays,
    required List<MealSlotDto> mealSlots,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(householdId, serializer);
          sse_encode_String(anchorDate, serializer);
          sse_encode_u_32(lengthDays, serializer);
          sse_encode_list_meal_slot_dto(mealSlots, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_planning_cycle_dto,
          decodeErrorData: sse_decode_kimatta_error,
        ),
        constMeta: kCrateApiPlanningSavePlanningCycleConstMeta,
        argValues: [householdId, anchorDate, lengthDays, mealSlots],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlanningSavePlanningCycleConstMeta =>
      const TaskConstMeta(
        debugName: "save_planning_cycle",
        argNames: ["householdId", "anchorDate", "lengthDays", "mealSlots"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  HealthReport dco_decode_health_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HealthReport(
      dbPath: dco_decode_String(arr[0]),
      schemaVersion: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  HouseholdDto dco_decode_household_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HouseholdDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      members: dco_decode_list_member_dto(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  KimattaError dco_decode_kimatta_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return KimattaError_InvalidPath();
      case 1:
        return KimattaError_NotOpen();
      case 2:
        return KimattaError_Storage(message: dco_decode_String(raw[1]));
      case 3:
        return KimattaError_Planning(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<MealSlotDto> dco_decode_list_meal_slot_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_meal_slot_dto).toList();
  }

  @protected
  List<MemberDto> dco_decode_list_member_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_member_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MealSlotDto dco_decode_meal_slot_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MealSlotDto.values[raw as int];
  }

  @protected
  MemberDto dco_decode_member_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MemberDto(
      id: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlanningCycleDto dco_decode_planning_cycle_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PlanningCycleDto(
      householdId: dco_decode_String(arr[0]),
      anchorDate: dco_decode_String(arr[1]),
      lengthDays: dco_decode_u_32(arr[2]),
      mealSlots: dco_decode_list_meal_slot_dto(arr[3]),
      dates: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  HealthReport sse_decode_health_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dbPath = sse_decode_String(deserializer);
    var var_schemaVersion = sse_decode_u_32(deserializer);
    return HealthReport(dbPath: var_dbPath, schemaVersion: var_schemaVersion);
  }

  @protected
  HouseholdDto sse_decode_household_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_members = sse_decode_list_member_dto(deserializer);
    return HouseholdDto(id: var_id, name: var_name, members: var_members);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  KimattaError sse_decode_kimatta_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return KimattaError_InvalidPath();
      case 1:
        return KimattaError_NotOpen();
      case 2:
        var var_message = sse_decode_String(deserializer);
        return KimattaError_Storage(message: var_message);
      case 3:
        var var_message = sse_decode_String(deserializer);
        return KimattaError_Planning(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<MealSlotDto> sse_decode_list_meal_slot_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MealSlotDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_meal_slot_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<MemberDto> sse_decode_list_member_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MemberDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_member_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MealSlotDto sse_decode_meal_slot_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MealSlotDto.values[inner];
  }

  @protected
  MemberDto sse_decode_member_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    return MemberDto(id: var_id, displayName: var_displayName);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlanningCycleDto sse_decode_planning_cycle_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_householdId = sse_decode_String(deserializer);
    var var_anchorDate = sse_decode_String(deserializer);
    var var_lengthDays = sse_decode_u_32(deserializer);
    var var_mealSlots = sse_decode_list_meal_slot_dto(deserializer);
    var var_dates = sse_decode_list_String(deserializer);
    return PlanningCycleDto(
      householdId: var_householdId,
      anchorDate: var_anchorDate,
      lengthDays: var_lengthDays,
      mealSlots: var_mealSlots,
      dates: var_dates,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_health_report(HealthReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.dbPath, serializer);
    sse_encode_u_32(self.schemaVersion, serializer);
  }

  @protected
  void sse_encode_household_dto(HouseholdDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_list_member_dto(self.members, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_kimatta_error(KimattaError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case KimattaError_InvalidPath():
        sse_encode_i_32(0, serializer);
      case KimattaError_NotOpen():
        sse_encode_i_32(1, serializer);
      case KimattaError_Storage(message: final message):
        sse_encode_i_32(2, serializer);
        sse_encode_String(message, serializer);
      case KimattaError_Planning(message: final message):
        sse_encode_i_32(3, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_meal_slot_dto(
    List<MealSlotDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_meal_slot_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_member_dto(
    List<MemberDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_member_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_meal_slot_dto(MealSlotDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_member_dto(MemberDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.displayName, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_planning_cycle_dto(
    PlanningCycleDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.householdId, serializer);
    sse_encode_String(self.anchorDate, serializer);
    sse_encode_u_32(self.lengthDays, serializer);
    sse_encode_list_meal_slot_dto(self.mealSlots, serializer);
    sse_encode_list_String(self.dates, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
