import 'package:flutter/material.dart';

enum PaletteChoice {
  aizomeLinen('Aizome · linen'),
  navyCream('Navy · cream'),
  sumiWashi('Sumi · washi'),
  eveningKitchen('Evening kitchen'),
  teaGarden('Tea garden'),
  rainyVeranda('Rainy veranda'),
  cedarClay('Cedar · clay');

  const PaletteChoice(this.label);

  final String label;
}

enum TypeChoice {
  shipporiAtkinson('Shippori + Atkinson'),
  zenOldAtkinson('Zen Old + Atkinson'),
  zenMaruAtkinson('Zen Maru + Atkinson'),
  atkinsonOnly('Atkinson only');

  const TypeChoice(this.label);

  final String label;
}

/// Palette anchors were authored in OKLCH, then committed as opaque sRGB tokens.
/// The source values and conversion provenance live beside the font provenance in
/// `assets/fonts/README.md`; no runtime color-generation dependency is needed.
final Map<(PaletteChoice, Brightness), ColorScheme> candidateColorSchemes = {
  (PaletteChoice.aizomeLinen, Brightness.light): _lightScheme(
    primary: const Color(0xFF29425F),
    primaryContainer: const Color(0xFFD7E0EA),
    secondary: const Color(0xFF475767),
    secondaryContainer: const Color(0xFFDDE2E5),
    accent: const Color(0xFF9B451F),
    accentContainer: const Color(0xFFF4D2B9),
    error: const Color(0xFF663D50),
    errorContainer: const Color(0xFFECD9E0),
    surface: const Color(0xFFF5EEDF),
    surfaceBright: const Color(0xFFFBF6EC),
    surfaceDim: const Color(0xFFDDD5C6),
    surfaceContainerLowest: const Color(0xFFFEFAF1),
    surfaceContainerLow: const Color(0xFFF0E8D9),
    surfaceContainer: const Color(0xFFEAE2D3),
    surfaceContainerHigh: const Color(0xFFE4DCCD),
    surfaceContainerHighest: const Color(0xFFDDD5C6),
    onSurface: const Color(0xFF252D36),
    onSurfaceVariant: const Color(0xFF4C5660),
    outline: const Color(0xFF6B737B),
    outlineVariant: const Color(0xFFB9B5AD),
    inverseSurface: const Color(0xFF303943),
    inversePrimary: const Color(0xFFB7C9DE),
  ),
  (PaletteChoice.aizomeLinen, Brightness.dark): _darkScheme(
    primary: const Color(0xFFC5D5E7),
    primaryContainer: const Color(0xFF344A63),
    secondary: const Color(0xFFBEC7CF),
    secondaryContainer: const Color(0xFF3E4A54),
    accent: const Color(0xFFFFB477),
    accentContainer: const Color(0xFF6C3516),
    error: const Color(0xFFDDB4C4),
    errorContainer: const Color(0xFF573442),
    surface: const Color(0xFF171E27),
    surfaceBright: const Color(0xFF343C46),
    surfaceDim: const Color(0xFF111820),
    surfaceContainerLowest: const Color(0xFF0E151D),
    surfaceContainerLow: const Color(0xFF1B232C),
    surfaceContainer: const Color(0xFF202832),
    surfaceContainerHigh: const Color(0xFF29313B),
    surfaceContainerHighest: const Color(0xFF343C46),
    onSurface: const Color(0xFFEDE5D7),
    onSurfaceVariant: const Color(0xFFCEC5B7),
    outline: const Color(0xFF9C958A),
    outlineVariant: const Color(0xFF4C5157),
    inverseSurface: const Color(0xFFEDE5D7),
    inversePrimary: const Color(0xFF29425F),
  ),
  (PaletteChoice.navyCream, Brightness.light): _lightScheme(
    primary: const Color(0xFF1F3A5F),
    primaryContainer: const Color(0xFFD5E0EF),
    secondary: const Color(0xFF4B5969),
    secondaryContainer: const Color(0xFFDCE2E9),
    accent: const Color(0xFF815200),
    accentContainer: const Color(0xFFF2D49B),
    error: const Color(0xFF633E55),
    errorContainer: const Color(0xFFEAD9E2),
    surface: const Color(0xFFF7F0DF),
    surfaceBright: const Color(0xFFFCF8EF),
    surfaceDim: const Color(0xFFDED5C2),
    surfaceContainerLowest: const Color(0xFFFFFBF2),
    surfaceContainerLow: const Color(0xFFF2EAD8),
    surfaceContainer: const Color(0xFFECE3D1),
    surfaceContainerHigh: const Color(0xFFE5DCCA),
    surfaceContainerHighest: const Color(0xFFDED5C2),
    onSurface: const Color(0xFF222C39),
    onSurfaceVariant: const Color(0xFF495463),
    outline: const Color(0xFF68727E),
    outlineVariant: const Color(0xFFB8B4AA),
    inverseSurface: const Color(0xFF2B3542),
    inversePrimary: const Color(0xFFB9CFEB),
  ),
  (PaletteChoice.navyCream, Brightness.dark): _darkScheme(
    primary: const Color(0xFFBDD1ED),
    primaryContainer: const Color(0xFF2C476A),
    secondary: const Color(0xFFC1CAD5),
    secondaryContainer: const Color(0xFF3D4957),
    accent: const Color(0xFFF3B55F),
    accentContainer: const Color(0xFF654312),
    error: const Color(0xFFDDB4C8),
    errorContainer: const Color(0xFF563445),
    surface: const Color(0xFF131B27),
    surfaceBright: const Color(0xFF303A48),
    surfaceDim: const Color(0xFF0F1620),
    surfaceContainerLowest: const Color(0xFF0C121B),
    surfaceContainerLow: const Color(0xFF18212D),
    surfaceContainer: const Color(0xFF1E2734),
    surfaceContainerHigh: const Color(0xFF27313E),
    surfaceContainerHighest: const Color(0xFF303A48),
    onSurface: const Color(0xFFF0E7D6),
    onSurfaceVariant: const Color(0xFFD0C6B5),
    outline: const Color(0xFFA0998D),
    outlineVariant: const Color(0xFF4A515B),
    inverseSurface: const Color(0xFFF0E7D6),
    inversePrimary: const Color(0xFF1F3A5F),
  ),
  (PaletteChoice.sumiWashi, Brightness.light): _lightScheme(
    primary: const Color(0xFF353638),
    primaryContainer: const Color(0xFFDDDDDA),
    secondary: const Color(0xFF55524C),
    secondaryContainer: const Color(0xFFE2DED5),
    accent: const Color(0xFF93411F),
    accentContainer: const Color(0xFFF1D0BB),
    error: const Color(0xFF62404F),
    errorContainer: const Color(0xFFE8D9DE),
    surface: const Color(0xFFF2EEE5),
    surfaceBright: const Color(0xFFFAF7F0),
    surfaceDim: const Color(0xFFDAD6CE),
    surfaceContainerLowest: const Color(0xFFFDFBF6),
    surfaceContainerLow: const Color(0xFFEDE9E0),
    surfaceContainer: const Color(0xFFE7E3DA),
    surfaceContainerHigh: const Color(0xFFE1DDD5),
    surfaceContainerHighest: const Color(0xFFDAD6CE),
    onSurface: const Color(0xFF292826),
    onSurfaceVariant: const Color(0xFF55524D),
    outline: const Color(0xFF716E68),
    outlineVariant: const Color(0xFFB9B5AE),
    inverseSurface: const Color(0xFF383633),
    inversePrimary: const Color(0xFFD5D0C7),
  ),
  (PaletteChoice.sumiWashi, Brightness.dark): _darkScheme(
    primary: const Color(0xFFD5D0C7),
    primaryContainer: const Color(0xFF484744),
    secondary: const Color(0xFFC9C4BA),
    secondaryContainer: const Color(0xFF4B4842),
    accent: const Color(0xFFF0A06A),
    accentContainer: const Color(0xFF69361D),
    error: const Color(0xFFD8B5C1),
    errorContainer: const Color(0xFF533641),
    surface: const Color(0xFF1D1C1A),
    surfaceBright: const Color(0xFF3C3A36),
    surfaceDim: const Color(0xFF171614),
    surfaceContainerLowest: const Color(0xFF131210),
    surfaceContainerLow: const Color(0xFF23211F),
    surfaceContainer: const Color(0xFF292724),
    surfaceContainerHigh: const Color(0xFF32302C),
    surfaceContainerHighest: const Color(0xFF3C3A36),
    onSurface: const Color(0xFFEAE4DA),
    onSurfaceVariant: const Color(0xFFCBC4B9),
    outline: const Color(0xFF9C968C),
    outlineVariant: const Color(0xFF504E49),
    inverseSurface: const Color(0xFFEAE4DA),
    inversePrimary: const Color(0xFF353638),
  ),
  (PaletteChoice.eveningKitchen, Brightness.light): _lightScheme(
    primary: const Color(0xFF2C315C),
    primaryContainer: const Color(0xFFDBDCF0),
    secondary: const Color(0xFF54566B),
    secondaryContainer: const Color(0xFFE1E0E8),
    accent: const Color(0xFF815200),
    accentContainer: const Color(0xFFF1D39A),
    error: const Color(0xFF62405A),
    errorContainer: const Color(0xFFE9D9E4),
    surface: const Color(0xFFEFE8D8),
    surfaceBright: const Color(0xFFF8F3E9),
    surfaceDim: const Color(0xFFD7CFBF),
    surfaceContainerLowest: const Color(0xFFFCF8EF),
    surfaceContainerLow: const Color(0xFFEAE2D2),
    surfaceContainer: const Color(0xFFE4DCCC),
    surfaceContainerHigh: const Color(0xFFDED6C6),
    surfaceContainerHighest: const Color(0xFFD7CFBF),
    onSurface: const Color(0xFF28293A),
    onSurfaceVariant: const Color(0xFF525365),
    outline: const Color(0xFF6E6F7D),
    outlineVariant: const Color(0xFFB5B1AA),
    inverseSurface: const Color(0xFF333447),
    inversePrimary: const Color(0xFFC8CBF2),
  ),
  (PaletteChoice.eveningKitchen, Brightness.dark): _darkScheme(
    primary: const Color(0xFFD4D6FF),
    primaryContainer: const Color(0xFF414772),
    secondary: const Color(0xFFC9C8DC),
    secondaryContainer: const Color(0xFF464757),
    accent: const Color(0xFFF3B55F),
    accentContainer: const Color(0xFF654312),
    error: const Color(0xFFDDB3CF),
    errorContainer: const Color(0xFF57344C),
    surface: const Color(0xFF121427),
    surfaceBright: const Color(0xFF31334A),
    surfaceDim: const Color(0xFF0E1021),
    surfaceContainerLowest: const Color(0xFF0B0D1B),
    surfaceContainerLow: const Color(0xFF181A2D),
    surfaceContainer: const Color(0xFF1E2034),
    surfaceContainerHigh: const Color(0xFF282A3E),
    surfaceContainerHighest: const Color(0xFF31334A),
    onSurface: const Color(0xFFEDE5D5),
    onSurfaceVariant: const Color(0xFFCEC5B6),
    outline: const Color(0xFF9E978C),
    outlineVariant: const Color(0xFF4B4D5D),
    inverseSurface: const Color(0xFFEDE5D5),
    inversePrimary: const Color(0xFF2C315C),
  ),
  (PaletteChoice.teaGarden, Brightness.light): _lightScheme(
    primary: const Color(0xFF35513E),
    primaryContainer: const Color(0xFFD7E3D8),
    secondary: const Color(0xFF4E5C51),
    secondaryContainer: const Color(0xFFDCE4DC),
    accent: const Color(0xFF8B4D23),
    accentContainer: const Color(0xFFF1D4BD),
    error: const Color(0xFF634151),
    errorContainer: const Color(0xFFE9DADD),
    surface: const Color(0xFFF4EFE2),
    surfaceBright: const Color(0xFFFBF7ED),
    surfaceDim: const Color(0xFFDCD7CA),
    surfaceContainerLowest: const Color(0xFFFEFAF2),
    surfaceContainerLow: const Color(0xFFEFEADD),
    surfaceContainer: const Color(0xFFE9E4D7),
    surfaceContainerHigh: const Color(0xFFE3DED1),
    surfaceContainerHighest: const Color(0xFFDCD7CA),
    onSurface: const Color(0xFF273029),
    onSurfaceVariant: const Color(0xFF4D5A50),
    outline: const Color(0xFF6B766C),
    outlineVariant: const Color(0xFFB6B8AF),
    inverseSurface: const Color(0xFF303A32),
    inversePrimary: const Color(0xFFBBD3BF),
  ),
  (PaletteChoice.teaGarden, Brightness.dark): _darkScheme(
    primary: const Color(0xFFC2DAC7),
    primaryContainer: const Color(0xFF34513D),
    secondary: const Color(0xFFC2CEC4),
    secondaryContainer: const Color(0xFF3D4B40),
    accent: const Color(0xFFF0AA70),
    accentContainer: const Color(0xFF65391D),
    error: const Color(0xFFDAB6C3),
    errorContainer: const Color(0xFF543640),
    surface: const Color(0xFF151D18),
    surfaceBright: const Color(0xFF333D35),
    surfaceDim: const Color(0xFF101812),
    surfaceContainerLowest: const Color(0xFF0D140F),
    surfaceContainerLow: const Color(0xFF1A231C),
    surfaceContainer: const Color(0xFF202A22),
    surfaceContainerHigh: const Color(0xFF29332B),
    surfaceContainerHighest: const Color(0xFF333D35),
    onSurface: const Color(0xFFEAE7DC),
    onSurfaceVariant: const Color(0xFFC9C8BA),
    outline: const Color(0xFF98998E),
    outlineVariant: const Color(0xFF4B514B),
    inverseSurface: const Color(0xFFEAE7DC),
    inversePrimary: const Color(0xFF35513E),
  ),
  (PaletteChoice.rainyVeranda, Brightness.light): _lightScheme(
    primary: const Color(0xFF365267),
    primaryContainer: const Color(0xFFD4E2EA),
    secondary: const Color(0xFF4D5A63),
    secondaryContainer: const Color(0xFFDCE2E5),
    accent: const Color(0xFF92502D),
    accentContainer: const Color(0xFFF2D3BF),
    error: const Color(0xFF653F52),
    errorContainer: const Color(0xFFEBD9E0),
    surface: const Color(0xFFF4EEE4),
    surfaceBright: const Color(0xFFFBF7EF),
    surfaceDim: const Color(0xFFDCD5CB),
    surfaceContainerLowest: const Color(0xFFFEFAF3),
    surfaceContainerLow: const Color(0xFFEFE9DF),
    surfaceContainer: const Color(0xFFE9E3D9),
    surfaceContainerHigh: const Color(0xFFE3DDD3),
    surfaceContainerHighest: const Color(0xFFDCD5CB),
    onSurface: const Color(0xFF253039),
    onSurfaceVariant: const Color(0xFF4D5860),
    outline: const Color(0xFF6B747A),
    outlineVariant: const Color(0xFFB7B6B1),
    inverseSurface: const Color(0xFF303A42),
    inversePrimary: const Color(0xFFBBD1DF),
  ),
  (PaletteChoice.rainyVeranda, Brightness.dark): _darkScheme(
    primary: const Color(0xFFC0D7E6),
    primaryContainer: const Color(0xFF344F61),
    secondary: const Color(0xFFC2CBD1),
    secondaryContainer: const Color(0xFF3D4950),
    accent: const Color(0xFFF1AD7B),
    accentContainer: const Color(0xFF683B23),
    error: const Color(0xFFDDB5C5),
    errorContainer: const Color(0xFF573542),
    surface: const Color(0xFF151C22),
    surfaceBright: const Color(0xFF333B42),
    surfaceDim: const Color(0xFF10171C),
    surfaceContainerLowest: const Color(0xFF0D1318),
    surfaceContainerLow: const Color(0xFF1A2228),
    surfaceContainer: const Color(0xFF20282E),
    surfaceContainerHigh: const Color(0xFF293139),
    surfaceContainerHighest: const Color(0xFF333B42),
    onSurface: const Color(0xFFECE6DC),
    onSurfaceVariant: const Color(0xFFCCC5BB),
    outline: const Color(0xFF9B968F),
    outlineVariant: const Color(0xFF4B5054),
    inverseSurface: const Color(0xFFECE6DC),
    inversePrimary: const Color(0xFF365267),
  ),
  (PaletteChoice.cedarClay, Brightness.light): _lightScheme(
    primary: const Color(0xFF55443C),
    primaryContainer: const Color(0xFFE7DCD5),
    secondary: const Color(0xFF60534C),
    secondaryContainer: const Color(0xFFE7DFDA),
    accent: const Color(0xFF8A491F),
    accentContainer: const Color(0xFFF1D2BA),
    error: const Color(0xFF65404C),
    errorContainer: const Color(0xFFEBD9DD),
    surface: const Color(0xFFF4EEE5),
    surfaceBright: const Color(0xFFFBF7F0),
    surfaceDim: const Color(0xFFDCD5CC),
    surfaceContainerLowest: const Color(0xFFFEFAF4),
    surfaceContainerLow: const Color(0xFFEFE9E0),
    surfaceContainer: const Color(0xFFE9E3DA),
    surfaceContainerHigh: const Color(0xFFE3DDD4),
    surfaceContainerHighest: const Color(0xFFDCD5CC),
    onSurface: const Color(0xFF302925),
    onSurfaceVariant: const Color(0xFF5A514B),
    outline: const Color(0xFF756D67),
    outlineVariant: const Color(0xFFBAB5B0),
    inverseSurface: const Color(0xFF3D3530),
    inversePrimary: const Color(0xFFD9C4B8),
  ),
  (PaletteChoice.cedarClay, Brightness.dark): _darkScheme(
    primary: const Color(0xFFDDC9BD),
    primaryContainer: const Color(0xFF5B453A),
    secondary: const Color(0xFFD0C4BC),
    secondaryContainer: const Color(0xFF50453F),
    accent: const Color(0xFFF3A56D),
    accentContainer: const Color(0xFF67371D),
    error: const Color(0xFFDEB4BF),
    errorContainer: const Color(0xFF57353D),
    surface: const Color(0xFF201A17),
    surfaceBright: const Color(0xFF403833),
    surfaceDim: const Color(0xFF191411),
    surfaceContainerLowest: const Color(0xFF15100E),
    surfaceContainerLow: const Color(0xFF261F1B),
    surfaceContainer: const Color(0xFF2C2521),
    surfaceContainerHigh: const Color(0xFF362E29),
    surfaceContainerHighest: const Color(0xFF403833),
    onSurface: const Color(0xFFEDE4DD),
    onSurfaceVariant: const Color(0xFFCEC2BA),
    outline: const Color(0xFF9F958F),
    outlineVariant: const Color(0xFF554D48),
    inverseSurface: const Color(0xFFEDE4DD),
    inversePrimary: const Color(0xFF55443C),
  ),
};

ColorScheme candidateColorScheme(
  PaletteChoice palette,
  Brightness brightness,
) => candidateColorSchemes[(palette, brightness)]!;

ThemeData buildTheme(
  PaletteChoice palette,
  TypeChoice type,
  Brightness brightness,
) {
  final scheme = candidateColorScheme(palette, brightness);
  final base = ThemeData(useMaterial3: true, colorScheme: scheme);
  return base.copyWith(
    scaffoldBackgroundColor: scheme.surface,
    textTheme: _pairedTextTheme(base.textTheme, type),
    primaryTextTheme: _pairedTextTheme(base.primaryTextTheme, type),
  );
}

TextTheme _pairedTextTheme(TextTheme base, TypeChoice type) {
  const body = 'Atkinson Hyperlegible';
  final display = switch (type) {
    TypeChoice.shipporiAtkinson => 'Shippori Mincho',
    TypeChoice.zenOldAtkinson => 'Zen Old Mincho',
    TypeChoice.zenMaruAtkinson => 'Zen Maru Gothic',
    TypeChoice.atkinsonOnly => body,
  };
  final bodyTheme = base.apply(fontFamily: body);
  TextStyle? displayStyle(TextStyle? style, {bool strong = false}) =>
      style?.copyWith(
        fontFamily: display,
        fontWeight: strong ? FontWeight.w700 : FontWeight.w400,
        height: 1.2,
      );
  TextStyle? bodyStyle(TextStyle? style, {bool strong = false}) =>
      style?.copyWith(
        fontFamily: body,
        fontWeight: strong ? FontWeight.w700 : FontWeight.w400,
        height: 1.35,
      );

  return bodyTheme.copyWith(
    displayLarge: displayStyle(bodyTheme.displayLarge),
    displayMedium: displayStyle(bodyTheme.displayMedium),
    displaySmall: displayStyle(bodyTheme.displaySmall),
    headlineLarge: displayStyle(bodyTheme.headlineLarge),
    headlineMedium: displayStyle(bodyTheme.headlineMedium),
    headlineSmall: displayStyle(bodyTheme.headlineSmall),
    titleLarge: displayStyle(bodyTheme.titleLarge, strong: true),
    titleMedium: bodyStyle(bodyTheme.titleMedium, strong: true),
    titleSmall: bodyStyle(bodyTheme.titleSmall, strong: true),
    bodyLarge: bodyStyle(bodyTheme.bodyLarge),
    bodyMedium: bodyStyle(bodyTheme.bodyMedium),
    bodySmall: bodyStyle(bodyTheme.bodySmall),
    labelLarge: bodyStyle(bodyTheme.labelLarge, strong: true),
    labelMedium: bodyStyle(bodyTheme.labelMedium, strong: true),
    labelSmall: bodyStyle(bodyTheme.labelSmall, strong: true),
  );
}

ColorScheme _lightScheme({
  required Color primary,
  required Color primaryContainer,
  required Color secondary,
  required Color secondaryContainer,
  required Color accent,
  required Color accentContainer,
  required Color error,
  required Color errorContainer,
  required Color surface,
  required Color surfaceBright,
  required Color surfaceDim,
  required Color surfaceContainerLowest,
  required Color surfaceContainerLow,
  required Color surfaceContainer,
  required Color surfaceContainerHigh,
  required Color surfaceContainerHighest,
  required Color onSurface,
  required Color onSurfaceVariant,
  required Color outline,
  required Color outlineVariant,
  required Color inverseSurface,
  required Color inversePrimary,
}) => ColorScheme(
  brightness: Brightness.light,
  primary: primary,
  onPrimary: surfaceBright,
  primaryContainer: primaryContainer,
  onPrimaryContainer: onSurface,
  primaryFixed: primary,
  primaryFixedDim: primary,
  onPrimaryFixed: surfaceBright,
  onPrimaryFixedVariant: surfaceBright,
  secondary: secondary,
  onSecondary: surfaceBright,
  secondaryContainer: secondaryContainer,
  onSecondaryContainer: onSurface,
  secondaryFixed: secondary,
  secondaryFixedDim: secondary,
  onSecondaryFixed: surfaceBright,
  onSecondaryFixedVariant: surfaceBright,
  tertiary: accent,
  onTertiary: surfaceBright,
  tertiaryContainer: accentContainer,
  onTertiaryContainer: onSurface,
  tertiaryFixed: accent,
  tertiaryFixedDim: accent,
  onTertiaryFixed: surfaceBright,
  onTertiaryFixedVariant: surfaceBright,
  error: error,
  onError: surfaceBright,
  errorContainer: errorContainer,
  onErrorContainer: onSurface,
  surface: surface,
  onSurface: onSurface,
  surfaceDim: surfaceDim,
  surfaceBright: surfaceBright,
  surfaceContainerLowest: surfaceContainerLowest,
  surfaceContainerLow: surfaceContainerLow,
  surfaceContainer: surfaceContainer,
  surfaceContainerHigh: surfaceContainerHigh,
  surfaceContainerHighest: surfaceContainerHighest,
  onSurfaceVariant: onSurfaceVariant,
  outline: outline,
  outlineVariant: outlineVariant,
  shadow: inverseSurface,
  scrim: inverseSurface,
  inverseSurface: inverseSurface,
  onInverseSurface: surface,
  inversePrimary: inversePrimary,
  surfaceTint: primary,
);

ColorScheme _darkScheme({
  required Color primary,
  required Color primaryContainer,
  required Color secondary,
  required Color secondaryContainer,
  required Color accent,
  required Color accentContainer,
  required Color error,
  required Color errorContainer,
  required Color surface,
  required Color surfaceBright,
  required Color surfaceDim,
  required Color surfaceContainerLowest,
  required Color surfaceContainerLow,
  required Color surfaceContainer,
  required Color surfaceContainerHigh,
  required Color surfaceContainerHighest,
  required Color onSurface,
  required Color onSurfaceVariant,
  required Color outline,
  required Color outlineVariant,
  required Color inverseSurface,
  required Color inversePrimary,
}) => ColorScheme(
  brightness: Brightness.dark,
  primary: primary,
  onPrimary: surfaceDim,
  primaryContainer: primaryContainer,
  onPrimaryContainer: onSurface,
  primaryFixed: primary,
  primaryFixedDim: primary,
  onPrimaryFixed: surfaceDim,
  onPrimaryFixedVariant: surfaceDim,
  secondary: secondary,
  onSecondary: surfaceDim,
  secondaryContainer: secondaryContainer,
  onSecondaryContainer: onSurface,
  secondaryFixed: secondary,
  secondaryFixedDim: secondary,
  onSecondaryFixed: surfaceDim,
  onSecondaryFixedVariant: surfaceDim,
  tertiary: accent,
  onTertiary: surfaceDim,
  tertiaryContainer: accentContainer,
  onTertiaryContainer: onSurface,
  tertiaryFixed: accent,
  tertiaryFixedDim: accent,
  onTertiaryFixed: surfaceDim,
  onTertiaryFixedVariant: surfaceDim,
  error: error,
  onError: surfaceDim,
  errorContainer: errorContainer,
  onErrorContainer: onSurface,
  surface: surface,
  onSurface: onSurface,
  surfaceDim: surfaceDim,
  surfaceBright: surfaceBright,
  surfaceContainerLowest: surfaceContainerLowest,
  surfaceContainerLow: surfaceContainerLow,
  surfaceContainer: surfaceContainer,
  surfaceContainerHigh: surfaceContainerHigh,
  surfaceContainerHighest: surfaceContainerHighest,
  onSurfaceVariant: onSurfaceVariant,
  outline: outline,
  outlineVariant: outlineVariant,
  shadow: surfaceContainerLowest,
  scrim: surfaceContainerLowest,
  inverseSurface: inverseSurface,
  onInverseSurface: surface,
  inversePrimary: inversePrimary,
  surfaceTint: primary,
);
