// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`, `from`, `from`

@freezed
sealed class KimattaError with _$KimattaError implements FrbException {
  const KimattaError._();

  const factory KimattaError.invalidPath() = KimattaError_InvalidPath;
  const factory KimattaError.notOpen() = KimattaError_NotOpen;
  const factory KimattaError.storage({required String message}) =
      KimattaError_Storage;
  const factory KimattaError.planning({required String message}) =
      KimattaError_Planning;
}
