// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String coreVersion() => RustLib.instance.api.crateApiHealthCoreVersion();

/// Opens the SQLite database at `db_path` (creating it), applies migrations, installs it as
/// the process-wide connection, and reports the schema version. Empty/whitespace paths are
/// rejected before touching storage. Calling again replaces the connection.
Future<HealthReport> openDatabase({required String dbPath}) =>
    RustLib.instance.api.crateApiHealthOpenDatabase(dbPath: dbPath);

class HealthReport {
  final String dbPath;
  final int schemaVersion;

  const HealthReport({required this.dbPath, required this.schemaVersion});

  @override
  int get hashCode => dbPath.hashCode ^ schemaVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HealthReport &&
          runtimeType == other.runtimeType &&
          dbPath == other.dbPath &&
          schemaVersion == other.schemaVersion;
}
