// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `rename_in`, `to_dto`

/// Returns the local household, creating an anonymous one-person household on the first
/// call (invariants 1 and 8). Later calls and later launches return the same ids.
Future<HouseholdDto> bootstrapHousehold() =>
    RustLib.instance.api.crateApiHouseholdBootstrapHousehold();

/// Renames exactly `household_id` (blank clears the name) and returns the updated household.
Future<HouseholdDto> renameHousehold({
  required String householdId,
  String? name,
}) => RustLib.instance.api.crateApiHouseholdRenameHousehold(
  householdId: householdId,
  name: name,
);

class HouseholdDto {
  final String id;
  final String? name;
  final List<MemberDto> members;

  const HouseholdDto({required this.id, this.name, required this.members});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ members.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HouseholdDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          members == other.members;
}

class MemberDto {
  final String id;
  final String displayName;

  const MemberDto({required this.id, required this.displayName});

  @override
  int get hashCode => id.hashCode ^ displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName;
}
