// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'recipe.dart';

// These functions are ignored because they are not marked as `pub`: `list_in`, `set_in`, `set_many_in`, `to_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Everything this household can mark — the catalog plus its own custom ingredients — each
/// with its current mark, ordered case-insensitively by name.
Future<List<PantryEntryDto>> listPantry({required String householdId}) =>
    RustLib.instance.api.crateApiPantryListPantry(householdId: householdId);

/// Marks or unmarks one identity and returns the entry as stored, mirroring
/// `save_restrictions`'s return-what-was-stored contract so the UI shows persisted truth.
/// Idempotent in both directions.
Future<PantryEntryDto> setPantryMark({
  required String householdId,
  required IngredientRefDto ingredient,
  required bool marked,
}) => RustLib.instance.api.crateApiPantrySetPantryMark(
  householdId: householdId,
  ingredient: ingredient,
  marked: marked,
);

/// Marks or unmarks every identity in one transaction and returns only the refs whose mark
/// actually changed — the set an Undo sends back, so a pre-existing mark is never cleared
/// (MVP-016 purchased→pantry). Any absent or foreign identity fails the whole batch.
Future<List<IngredientRefDto>> setPantryMarks({
  required String householdId,
  required List<IngredientRefDto> ingredients,
  required bool marked,
}) => RustLib.instance.api.crateApiPantrySetPantryMarks(
  householdId: householdId,
  ingredients: ingredients,
  marked: marked,
);

/// One browsable identity with this household's mark. `marked` means *the household marked this
/// as one it has*; `false` means **no record** — unknown, never an assertion that the household
/// lacks it (invariant 6, PRD §10). `MVP-015`/`MVP-016` must read it that way. `ingredient`
/// reuses `recipe.rs`'s `IngredientRefDto` rather than minting a second identity type, as
/// `recipe.rs` itself reuses `restrictions.rs`'s `RestrictionDto`.
class PantryEntryDto {
  final IngredientRefDto ingredient;
  final String name;
  final List<String> aliases;
  final bool marked;

  const PantryEntryDto({
    required this.ingredient,
    required this.name,
    required this.aliases,
    required this.marked,
  });

  @override
  int get hashCode =>
      ingredient.hashCode ^ name.hashCode ^ aliases.hashCode ^ marked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PantryEntryDto &&
          runtimeType == other.runtimeType &&
          ingredient == other.ingredient &&
          name == other.name &&
          aliases == other.aliases &&
          marked == other.marked;
}
