// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'planned_meals.dart';
import 'planning.dart';

// These functions are ignored because they are not marked as `pub`: `attention_from_domain`, `band_from_domain`, `codes`, `components_from_domain`, `confidence_from_domain`, `cover_in`, `proposal_from_domain`, `result_from_domain`, `source_from_domain`, `state_from_domain`, `status_from_domain`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Loads, assesses, plans, records — and applies when asked and safe — in one command.
Future<CoverCycleOutcomeDto> coverCycle({
  required CoverCycleRequestDto request,
}) => RustLib.instance.api.crateApiPlannerCoverCycle(request: request);

class ActionProposalDto {
  final String id;
  final String controllerId;
  final String actionType;
  final BandDto expectedBenefitBand;
  final ConfidenceDto confidence;
  final ReversibilityDto reversibility;
  final RequiredAuthorityDto requiredAuthority;
  final String? deadline;
  final List<String> reasonCodes;

  const ActionProposalDto({
    required this.id,
    required this.controllerId,
    required this.actionType,
    required this.expectedBenefitBand,
    required this.confidence,
    required this.reversibility,
    required this.requiredAuthority,
    this.deadline,
    required this.reasonCodes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      controllerId.hashCode ^
      actionType.hashCode ^
      expectedBenefitBand.hashCode ^
      confidence.hashCode ^
      reversibility.hashCode ^
      requiredAuthority.hashCode ^
      deadline.hashCode ^
      reasonCodes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActionProposalDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          controllerId == other.controllerId &&
          actionType == other.actionType &&
          expectedBenefitBand == other.expectedBenefitBand &&
          confidence == other.confidence &&
          reversibility == other.reversibility &&
          requiredAuthority == other.requiredAuthority &&
          deadline == other.deadline &&
          reasonCodes == other.reasonCodes;
}

class AttentionRequestDto {
  final String id;
  final String controllerId;
  final UrgencyDto urgency;
  final String? deadline;
  final BandDto decisionBenefitBand;
  final BandDto estimatedEffortBand;
  final List<String> options;
  final List<String> reasonCodes;

  const AttentionRequestDto({
    required this.id,
    required this.controllerId,
    required this.urgency,
    this.deadline,
    required this.decisionBenefitBand,
    required this.estimatedEffortBand,
    required this.options,
    required this.reasonCodes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      controllerId.hashCode ^
      urgency.hashCode ^
      deadline.hashCode ^
      decisionBenefitBand.hashCode ^
      estimatedEffortBand.hashCode ^
      options.hashCode ^
      reasonCodes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttentionRequestDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          controllerId == other.controllerId &&
          urgency == other.urgency &&
          deadline == other.deadline &&
          decisionBenefitBand == other.decisionBenefitBand &&
          estimatedEffortBand == other.estimatedEffortBand &&
          options == other.options &&
          reasonCodes == other.reasonCodes;
}

enum BandDto { low, medium, high }

enum CandidateSourceDto {
  existingPlan,
  householdRecipe,
  starterMeal,
  leftovers,
  diningOut,
  frozenQuick,
  intentionallyOpen,
}

enum ConfidenceDto { explicit, high, low, unknown }

class CoverCycleOutcomeDto {
  final PlanningResultDto result;
  final String ledgerEntryId;
  final bool applied;
  final int changedSlots;

  const CoverCycleOutcomeDto({
    required this.result,
    required this.ledgerEntryId,
    required this.applied,
    required this.changedSlots,
  });

  @override
  int get hashCode =>
      result.hashCode ^
      ledgerEntryId.hashCode ^
      applied.hashCode ^
      changedSlots.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoverCycleOutcomeDto &&
          runtimeType == other.runtimeType &&
          result == other.result &&
          ledgerEntryId == other.ledgerEntryId &&
          applied == other.applied &&
          changedSlots == other.changedSlots;
}

class CoverCycleRequestDto {
  final String householdId;

  /// ISO civil date.
  final String today;

  /// 0 is the active window, as `planning_cycle_window` counts.
  final int offsetCycles;

  /// `true` also writes the plan (unlocked, changed slots only) when its status is not
  /// `NeedsAttention`; the outcome says whether that happened.
  final bool apply;

  /// Absent fields take the recorded defaults (B=8, K=12, horizon 2 days).
  final int? beamWidth;
  final int? candidatesPerSlot;
  final int? commitmentHorizonDays;

  const CoverCycleRequestDto({
    required this.householdId,
    required this.today,
    required this.offsetCycles,
    required this.apply,
    this.beamWidth,
    this.candidatesPerSlot,
    this.commitmentHorizonDays,
  });

  @override
  int get hashCode =>
      householdId.hashCode ^
      today.hashCode ^
      offsetCycles.hashCode ^
      apply.hashCode ^
      beamWidth.hashCode ^
      candidatesPerSlot.hashCode ^
      commitmentHorizonDays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoverCycleRequestDto &&
          runtimeType == other.runtimeType &&
          householdId == other.householdId &&
          today == other.today &&
          offsetCycles == other.offsetCycles &&
          apply == other.apply &&
          beamWidth == other.beamWidth &&
          candidatesPerSlot == other.candidatesPerSlot &&
          commitmentHorizonDays == other.commitmentHorizonDays;
}

enum CoverageStateDto {
  unresolved,
  tentativelyCovered,
  covered,
  lockedByUser,
  intentionallyOpen,
  needsAttention,
}

enum OutcomeStatusDto {
  unresolved,
  tentativelyCovered,
  covered,
  needsAttention,
}

class PlanningResultDto {
  final int algorithmVersion;
  final String snapshotHash;
  final OutcomeStatusDto status;

  /// Inclusive ISO bounds of the planned window.
  final String horizonFrom;
  final String horizonTo;
  final List<SlotCoverageDto> slots;
  final List<ProposedMealDto> proposed;
  final List<RejectionDto> rejections;
  final List<String> unresolvedIssues;
  final List<String> assumptions;
  final List<String> reasonCodes;
  final List<ActionProposalDto> proposals;
  final List<AttentionRequestDto> attention;
  final SearchTraceDto search;

  /// The six lexicographic tier totals, best plan.
  final Int64List scoreTiers;

  const PlanningResultDto({
    required this.algorithmVersion,
    required this.snapshotHash,
    required this.status,
    required this.horizonFrom,
    required this.horizonTo,
    required this.slots,
    required this.proposed,
    required this.rejections,
    required this.unresolvedIssues,
    required this.assumptions,
    required this.reasonCodes,
    required this.proposals,
    required this.attention,
    required this.search,
    required this.scoreTiers,
  });

  @override
  int get hashCode =>
      algorithmVersion.hashCode ^
      snapshotHash.hashCode ^
      status.hashCode ^
      horizonFrom.hashCode ^
      horizonTo.hashCode ^
      slots.hashCode ^
      proposed.hashCode ^
      rejections.hashCode ^
      unresolvedIssues.hashCode ^
      assumptions.hashCode ^
      reasonCodes.hashCode ^
      proposals.hashCode ^
      attention.hashCode ^
      search.hashCode ^
      scoreTiers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlanningResultDto &&
          runtimeType == other.runtimeType &&
          algorithmVersion == other.algorithmVersion &&
          snapshotHash == other.snapshotHash &&
          status == other.status &&
          horizonFrom == other.horizonFrom &&
          horizonTo == other.horizonTo &&
          slots == other.slots &&
          proposed == other.proposed &&
          rejections == other.rejections &&
          unresolvedIssues == other.unresolvedIssues &&
          assumptions == other.assumptions &&
          reasonCodes == other.reasonCodes &&
          proposals == other.proposals &&
          attention == other.attention &&
          search == other.search &&
          scoreTiers == other.scoreTiers;
}

class ProposedMealDto {
  final String date;
  final MealSlotDto slot;
  final List<MealComponentDto> components;

  const ProposedMealDto({
    required this.date,
    required this.slot,
    required this.components,
  });

  @override
  int get hashCode => date.hashCode ^ slot.hashCode ^ components.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProposedMealDto &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          slot == other.slot &&
          components == other.components;
}

class RejectionDto {
  final String date;
  final MealSlotDto slot;
  final String candidateText;
  final String code;

  const RejectionDto({
    required this.date,
    required this.slot,
    required this.candidateText,
    required this.code,
  });

  @override
  int get hashCode =>
      date.hashCode ^ slot.hashCode ^ candidateText.hashCode ^ code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RejectionDto &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          slot == other.slot &&
          candidateText == other.candidateText &&
          code == other.code;
}

enum RequiredAuthorityDto { none, householdMember }

enum ReversibilityDto { reversible, irreversible }

class SearchTraceDto {
  final int beamWidth;
  final int candidatesPerSlot;
  final String slotOrder;
  final int statesScored;

  const SearchTraceDto({
    required this.beamWidth,
    required this.candidatesPerSlot,
    required this.slotOrder,
    required this.statesScored,
  });

  @override
  int get hashCode =>
      beamWidth.hashCode ^
      candidatesPerSlot.hashCode ^
      slotOrder.hashCode ^
      statesScored.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchTraceDto &&
          runtimeType == other.runtimeType &&
          beamWidth == other.beamWidth &&
          candidatesPerSlot == other.candidatesPerSlot &&
          slotOrder == other.slotOrder &&
          statesScored == other.statesScored;
}

class SlotCoverageDto {
  /// ISO civil date.
  final String date;
  final MealSlotDto slot;
  final CoverageStateDto state;
  final CandidateSourceDto? source;
  final List<MealComponentDto> components;
  final List<String> reasonCodes;

  const SlotCoverageDto({
    required this.date,
    required this.slot,
    required this.state,
    this.source,
    required this.components,
    required this.reasonCodes,
  });

  @override
  int get hashCode =>
      date.hashCode ^
      slot.hashCode ^
      state.hashCode ^
      source.hashCode ^
      components.hashCode ^
      reasonCodes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SlotCoverageDto &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          slot == other.slot &&
          state == other.state &&
          source == other.source &&
          components == other.components &&
          reasonCodes == other.reasonCodes;
}

enum UrgencyDto { low, high }
