// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_in`, `from_domain`, `save_in`, `to_domain`, `to_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `fmt`

/// Returns the household's planning cycle, creating the dinner-only seven-day default
/// anchored at `default_anchor_date` if none exists. The anchor is supplied by the caller
/// because "today" is a local civil date the platform owns; Rust never reads the clock, so
/// every value here is a pure function of its inputs (PRD v3 §8, invariant 20).
Future<PlanningCycleDto> ensurePlanningCycle({
  required String householdId,
  required String defaultAnchorDate,
}) => RustLib.instance.api.crateApiPlanningEnsurePlanningCycle(
  householdId: householdId,
  defaultAnchorDate: defaultAnchorDate,
);

/// Replaces the household's cycle and meal scope, and returns what was stored.
Future<PlanningCycleDto> savePlanningCycle({
  required String householdId,
  required String anchorDate,
  required int lengthDays,
  required List<MealSlotDto> mealSlots,
}) => RustLib.instance.api.crateApiPlanningSavePlanningCycle(
  householdId: householdId,
  anchorDate: anchorDate,
  lengthDays: lengthDays,
  mealSlots: mealSlots,
);

enum MealSlotDto { breakfast, lunch, dinner }

class PlanningCycleDto {
  final String householdId;
  final String anchorDate;
  final int lengthDays;
  final List<MealSlotDto> mealSlots;
  final List<String> dates;

  const PlanningCycleDto({
    required this.householdId,
    required this.anchorDate,
    required this.lengthDays,
    required this.mealSlots,
    required this.dates,
  });

  @override
  int get hashCode =>
      householdId.hashCode ^
      anchorDate.hashCode ^
      lengthDays.hashCode ^
      mealSlots.hashCode ^
      dates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlanningCycleDto &&
          runtimeType == other.runtimeType &&
          householdId == other.householdId &&
          anchorDate == other.anchorDate &&
          lengthDays == other.lengthDays &&
          mealSlots == other.mealSlots &&
          dates == other.dates;
}
