// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import 'planned_meals.dart';
import 'planner.dart';
import 'planning.dart';
part 'planning_drafts.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `accept_in`, `action_to_domain`, `context_to_domain`, `envelope_to_domain`, `exclusion_outcome_to_dto`, `exclusion_to_dto`, `mutate_in`, `open_in`, `origin_to_dto`, `outcome_to_dto`, `slot_to_dto`, `state_to_dto`, `view_to_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<List<MealExclusionDto>> listMealExclusions({
  required String householdId,
}) => RustLib.instance.api.crateApiPlanningDraftsListMealExclusions(
  householdId: householdId,
);

Future<MealExclusionOutcomeDto> addMealExclusions({
  required AddMealExclusionsDto request,
}) => RustLib.instance.api.crateApiPlanningDraftsAddMealExclusions(
  request: request,
);

Future<MealExclusionOutcomeDto> removeMealExclusion({
  required RemoveMealExclusionDto request,
}) => RustLib.instance.api.crateApiPlanningDraftsRemoveMealExclusion(
  request: request,
);

/// Resumes this window's draft, or starts one from the saved meals. Returns the session every
/// later command must carry.
Future<DraftViewDto> openPlanningDraft({required DraftContextDto context}) =>
    RustLib.instance.api.crateApiPlanningDraftsOpenPlanningDraft(
      context: context,
    );

/// A read-only look at one draft, expired ones included.
Future<DraftViewDto> inspectPlanningDraft({
  required DraftContextDto context,
  required String draftId,
}) => RustLib.instance.api.crateApiPlanningDraftsInspectPlanningDraft(
  context: context,
  draftId: draftId,
);

Future<DraftViewDto> mutatePlanningDraft({
  required DraftEnvelopeDto envelope,
  required DraftActionDto action,
}) => RustLib.instance.api.crateApiPlanningDraftsMutatePlanningDraft(
  envelope: envelope,
  action: action,
);

Future<DraftViewDto> acceptPlanningDraft({
  required DraftEnvelopeDto envelope,
}) => RustLib.instance.api.crateApiPlanningDraftsAcceptPlanningDraft(
  envelope: envelope,
);

class AcceptReceiptDto {
  final String ledgerEntryId;
  final int changedSlots;

  const AcceptReceiptDto({
    required this.ledgerEntryId,
    required this.changedSlots,
  });

  @override
  int get hashCode => ledgerEntryId.hashCode ^ changedSlots.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AcceptReceiptDto &&
          runtimeType == other.runtimeType &&
          ledgerEntryId == other.ledgerEntryId &&
          changedSlots == other.changedSlots;
}

class AddMealExclusionsDto {
  final DraftContextDto context;

  /// Dish identities the household confirmed.
  final List<String> dishes;

  /// The draft the rule was made from, re-assessed and returned with its choices kept.
  final DraftEnvelopeDto? acting;

  const AddMealExclusionsDto({
    required this.context,
    required this.dishes,
    this.acting,
  });

  @override
  int get hashCode => context.hashCode ^ dishes.hashCode ^ acting.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddMealExclusionsDto &&
          runtimeType == other.runtimeType &&
          context == other.context &&
          dishes == other.dishes &&
          acting == other.acting;
}

@freezed
sealed class DraftActionDto with _$DraftActionDto {
  const DraftActionDto._();

  const factory DraftActionDto.another({
    required String date,
    required MealSlotDto slot,
  }) = DraftActionDto_Another;
  const factory DraftActionDto.alternatives() = DraftActionDto_Alternatives;
  const factory DraftActionDto.setCommitment({
    required String date,
    required MealSlotDto slot,
    required bool locked,
  }) = DraftActionDto_SetCommitment;
  const factory DraftActionDto.choose({
    required String date,
    required MealSlotDto slot,
    required List<MealComponentDto> components,
    required bool explicitReplace,
  }) = DraftActionDto_Choose;
  const factory DraftActionDto.undo() = DraftActionDto_Undo;
  const factory DraftActionDto.discard() = DraftActionDto_Discard;

  /// Both `None` clears every exclusion in the draft.
  const factory DraftActionDto.reconsider({String? date, MealSlotDto? slot}) =
      DraftActionDto_Reconsider;
  const factory DraftActionDto.review({
    required List<ReviewResolutionDto> resolutions,
  }) = DraftActionDto_Review;
}

class DraftContextDto {
  final String householdId;

  /// ISO civil date.
  final String today;

  /// 0 is the active window, as `planning_cycle_window` counts.
  final int offsetCycles;

  const DraftContextDto({
    required this.householdId,
    required this.today,
    required this.offsetCycles,
  });

  @override
  int get hashCode =>
      householdId.hashCode ^ today.hashCode ^ offsetCycles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DraftContextDto &&
          runtimeType == other.runtimeType &&
          householdId == other.householdId &&
          today == other.today &&
          offsetCycles == other.offsetCycles;
}

class DraftEnvelopeDto {
  final DraftContextDto context;

  /// From the view this command was built on.
  final String databaseSession;
  final String draftId;
  final PlatformInt64 expectedRevision;

  /// Fresh per user intent; a retry of the same intent reuses it.
  final String requestId;

  const DraftEnvelopeDto({
    required this.context,
    required this.databaseSession,
    required this.draftId,
    required this.expectedRevision,
    required this.requestId,
  });

  @override
  int get hashCode =>
      context.hashCode ^
      databaseSession.hashCode ^
      draftId.hashCode ^
      expectedRevision.hashCode ^
      requestId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DraftEnvelopeDto &&
          runtimeType == other.runtimeType &&
          context == other.context &&
          databaseSession == other.databaseSession &&
          draftId == other.draftId &&
          expectedRevision == other.expectedRevision &&
          requestId == other.requestId;
}

class DraftOperationDto {
  final String operation;
  final List<SlotOutcomeRecordDto> slots;

  const DraftOperationDto({required this.operation, required this.slots});

  @override
  int get hashCode => operation.hashCode ^ slots.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DraftOperationDto &&
          runtimeType == other.runtimeType &&
          operation == other.operation &&
          slots == other.slots;
}

class DraftSlotDto {
  final String date;
  final MealSlotDto slot;
  final List<MealComponentDto> components;
  final SlotOriginDto origin;
  final bool committed;
  final SavedMealDto? saved;
  final bool editable;
  final bool pending;
  final bool inReview;
  final CoverageStateDto state;

  /// Engine tokens; the UI maps the ones it knows and never renders a raw one.
  final List<String> reasonCodes;
  final SlotOutcomeDto? outcome;
  final int excluded;

  const DraftSlotDto({
    required this.date,
    required this.slot,
    required this.components,
    required this.origin,
    required this.committed,
    this.saved,
    required this.editable,
    required this.pending,
    required this.inReview,
    required this.state,
    required this.reasonCodes,
    this.outcome,
    required this.excluded,
  });

  @override
  int get hashCode =>
      date.hashCode ^
      slot.hashCode ^
      components.hashCode ^
      origin.hashCode ^
      committed.hashCode ^
      saved.hashCode ^
      editable.hashCode ^
      pending.hashCode ^
      inReview.hashCode ^
      state.hashCode ^
      reasonCodes.hashCode ^
      outcome.hashCode ^
      excluded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DraftSlotDto &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          slot == other.slot &&
          components == other.components &&
          origin == other.origin &&
          committed == other.committed &&
          saved == other.saved &&
          editable == other.editable &&
          pending == other.pending &&
          inReview == other.inReview &&
          state == other.state &&
          reasonCodes == other.reasonCodes &&
          outcome == other.outcome &&
          excluded == other.excluded;
}

enum DraftStateDto { active, needsReview, accepted, discarded, expired }

class DraftViewDto {
  final String databaseSession;
  final String draftId;
  final PlatformInt64 revision;
  final DraftStateDto state;
  final String anchor;
  final int lengthDays;
  final List<DraftSlotDto> slots;
  final OutcomeStatusDto status;
  final List<String> unresolvedIssues;
  final List<String> assumptions;
  final bool acceptAllowed;
  final bool undoAvailable;
  final bool pendingChanges;
  final int weekTargets;
  final int excluded;
  final int pastChangesDropped;
  final DraftOperationDto? operation;
  final AcceptReceiptDto? receipt;
  final List<ExpiredDraftDto> expired;

  const DraftViewDto({
    required this.databaseSession,
    required this.draftId,
    required this.revision,
    required this.state,
    required this.anchor,
    required this.lengthDays,
    required this.slots,
    required this.status,
    required this.unresolvedIssues,
    required this.assumptions,
    required this.acceptAllowed,
    required this.undoAvailable,
    required this.pendingChanges,
    required this.weekTargets,
    required this.excluded,
    required this.pastChangesDropped,
    this.operation,
    this.receipt,
    required this.expired,
  });

  @override
  int get hashCode =>
      databaseSession.hashCode ^
      draftId.hashCode ^
      revision.hashCode ^
      state.hashCode ^
      anchor.hashCode ^
      lengthDays.hashCode ^
      slots.hashCode ^
      status.hashCode ^
      unresolvedIssues.hashCode ^
      assumptions.hashCode ^
      acceptAllowed.hashCode ^
      undoAvailable.hashCode ^
      pendingChanges.hashCode ^
      weekTargets.hashCode ^
      excluded.hashCode ^
      pastChangesDropped.hashCode ^
      operation.hashCode ^
      receipt.hashCode ^
      expired.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DraftViewDto &&
          runtimeType == other.runtimeType &&
          databaseSession == other.databaseSession &&
          draftId == other.draftId &&
          revision == other.revision &&
          state == other.state &&
          anchor == other.anchor &&
          lengthDays == other.lengthDays &&
          slots == other.slots &&
          status == other.status &&
          unresolvedIssues == other.unresolvedIssues &&
          assumptions == other.assumptions &&
          acceptAllowed == other.acceptAllowed &&
          undoAvailable == other.undoAvailable &&
          pendingChanges == other.pendingChanges &&
          weekTargets == other.weekTargets &&
          excluded == other.excluded &&
          pastChangesDropped == other.pastChangesDropped &&
          operation == other.operation &&
          receipt == other.receipt &&
          expired == other.expired;
}

class ExpiredDraftDto {
  final String draftId;
  final String anchor;
  final int lengthDays;

  const ExpiredDraftDto({
    required this.draftId,
    required this.anchor,
    required this.lengthDays,
  });

  @override
  int get hashCode => draftId.hashCode ^ anchor.hashCode ^ lengthDays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExpiredDraftDto &&
          runtimeType == other.runtimeType &&
          draftId == other.draftId &&
          anchor == other.anchor &&
          lengthDays == other.lengthDays;
}

class MealExclusionDto {
  final String policyId;
  final MealExclusionKindDto kind;

  const MealExclusionDto({required this.policyId, required this.kind});

  @override
  int get hashCode => policyId.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MealExclusionDto &&
          runtimeType == other.runtimeType &&
          policyId == other.policyId &&
          kind == other.kind;
}

@freezed
sealed class MealExclusionKindDto with _$MealExclusionKindDto {
  const MealExclusionKindDto._();

  /// Exactly this dish (`recipe:<id>` / `starter:<slug>`), whatever it is called.
  const factory MealExclusionKindDto.dish({
    required String identity,
    String? title,
    required bool available,
  }) = MealExclusionKindDto_Dish;

  /// A legacy rule: the words match any title or ingredient line.
  const factory MealExclusionKindDto.phrase({required String subject}) =
      MealExclusionKindDto_Phrase;
}

class MealExclusionOutcomeDto {
  final List<MealExclusionDto> exclusions;
  final DraftViewDto? draft;

  const MealExclusionOutcomeDto({required this.exclusions, this.draft});

  @override
  int get hashCode => exclusions.hashCode ^ draft.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MealExclusionOutcomeDto &&
          runtimeType == other.runtimeType &&
          exclusions == other.exclusions &&
          draft == other.draft;
}

class RemoveMealExclusionDto {
  final DraftContextDto context;
  final String policyId;
  final DraftEnvelopeDto? acting;

  const RemoveMealExclusionDto({
    required this.context,
    required this.policyId,
    this.acting,
  });

  @override
  int get hashCode => context.hashCode ^ policyId.hashCode ^ acting.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoveMealExclusionDto &&
          runtimeType == other.runtimeType &&
          context == other.context &&
          policyId == other.policyId &&
          acting == other.acting;
}

class ReviewResolutionDto {
  final String date;
  final MealSlotDto slot;
  final bool useSaved;

  const ReviewResolutionDto({
    required this.date,
    required this.slot,
    required this.useSaved,
  });

  @override
  int get hashCode => date.hashCode ^ slot.hashCode ^ useSaved.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewResolutionDto &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          slot == other.slot &&
          useSaved == other.useSaved;
}

class SavedMealDto {
  final List<MealComponentDto> components;
  final bool locked;

  const SavedMealDto({required this.components, required this.locked});

  @override
  int get hashCode => components.hashCode ^ locked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SavedMealDto &&
          runtimeType == other.runtimeType &&
          components == other.components &&
          locked == other.locked;
}

enum SlotOriginDto { empty, saved, suggested, chosen }

enum SlotOutcomeDto { changed, exhausted, blocked }

class SlotOutcomeRecordDto {
  final String date;
  final MealSlotDto slot;
  final SlotOutcomeDto outcome;

  const SlotOutcomeRecordDto({
    required this.date,
    required this.slot,
    required this.outcome,
  });

  @override
  int get hashCode => date.hashCode ^ slot.hashCode ^ outcome.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SlotOutcomeRecordDto &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          slot == other.slot &&
          outcome == other.outcome;
}
