// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'planning.dart';

// These functions are ignored because they are not marked as `pub`: `component_from_domain`, `component_to_domain`, `delete_in`, `from_domain`, `list_in`, `load_in`, `lock_in`, `save_in`, `stored`, `to_domain`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

/// Saves the whole occurrence and returns what was stored. Always a user write: automation
/// never crosses the bridge (MVP-023 calls storage directly with `WriteSource::Automation`).
Future<PlannedMealDto> savePlannedMeal({required PlannedMealDto meal}) =>
    RustLib.instance.api.crateApiPlannedMealsSavePlannedMeal(meal: meal);

/// The occurrence in exactly `household_id`, or `None`.
Future<PlannedMealDto?> loadPlannedMeal({
  required String householdId,
  required String mealId,
}) => RustLib.instance.api.crateApiPlannedMealsLoadPlannedMeal(
  householdId: householdId,
  mealId: mealId,
);

/// Occurrences dated `from_date..=to_date`, by date then slot.
Future<List<PlannedMealDto>> listPlannedMeals({
  required String householdId,
  required String fromDate,
  required String toDate,
}) => RustLib.instance.api.crateApiPlannedMealsListPlannedMeals(
  householdId: householdId,
  fromDate: fromDate,
  toDate: toDate,
);

/// Sets or clears the user's lock; returns the occurrence as stored.
Future<PlannedMealDto> setPlannedMealLock({
  required String householdId,
  required String mealId,
  required bool locked,
}) => RustLib.instance.api.crateApiPlannedMealsSetPlannedMealLock(
  householdId: householdId,
  mealId: mealId,
  locked: locked,
);

Future<void> deletePlannedMeal({
  required String householdId,
  required String mealId,
}) => RustLib.instance.api.crateApiPlannedMealsDeletePlannedMeal(
  householdId: householdId,
  mealId: mealId,
);

/// The component kind vocabulary, one source for a picker (as `known_unit_kinds` is).
Future<List<String>> knownMealComponentKinds() =>
    RustLib.instance.api.crateApiPlannedMealsKnownMealComponentKinds();

/// `kind` is a `MealComponent` token (`recipe`, `leftovers`, `dining_out`, `frozen_quick`,
/// `freeform`, `open`), carried as a string for the reason `UnitDto`/`RestrictionDto` give.
/// `recipe_id` and `scale` belong to `recipe` only; `note` to the rest, required for
/// `freeform`. Any other pairing is a typed `PlannedMeal` error.
class MealComponentDto {
  final String kind;
  final String? recipeId;
  final String? note;
  final ScaleDto? scale;

  const MealComponentDto({
    required this.kind,
    this.recipeId,
    this.note,
    this.scale,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ recipeId.hashCode ^ note.hashCode ^ scale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MealComponentDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          recipeId == other.recipeId &&
          note == other.note &&
          scale == other.scale;
}

class PlannedMealDto {
  /// Blank mints a v4 UUID, as `RecipeDto.id` does.
  final String id;
  final String householdId;

  /// ISO civil date.
  final String date;
  final MealSlotDto slot;
  final List<MealComponentDto> components;

  /// **Output only** on save: `save_planned_meal` ignores it and never changes lock state;
  /// use `set_planned_meal_lock`. Every read-back reports the stored value.
  final bool locked;

  const PlannedMealDto({
    required this.id,
    required this.householdId,
    required this.date,
    required this.slot,
    required this.components,
    required this.locked,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      householdId.hashCode ^
      date.hashCode ^
      slot.hashCode ^
      components.hashCode ^
      locked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlannedMealDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          householdId == other.householdId &&
          date == other.date &&
          slot == other.slot &&
          components == other.components &&
          locked == other.locked;
}

/// A serving multiplier of the recipe as written; absent means 1×.
class ScaleDto {
  final int numer;
  final int denom;

  const ScaleDto({required this.numer, required this.denom});

  @override
  int get hashCode => numer.hashCode ^ denom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScaleDto &&
          runtimeType == other.runtimeType &&
          numer == other.numer &&
          denom == other.denom;
}
