// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import 'restrictions.dart';
part 'recipe.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `add_custom_ingredient_in`, `archive_recipe_in`, `assess_names`, `assessment_from_domain`, `custom_from_domain`, `id_or_minted`, `line_from_domain`, `line_to_domain`, `list_archived_recipes_in`, `list_custom_ingredients_in`, `list_recipes_in`, `load_recipe_in`, `quantity_from_domain`, `quantity_to_domain`, `rational`, `recipe_from_domain`, `recipe_to_domain`, `restore_recipe_in`, `save_recipe_in`, `stored_recipe`, `summaries`, `unit_from_domain`, `unit_to_domain`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Saves the whole recipe; an empty `id` mints a v4 UUID (as `bootstrap_household` does).
/// Returns what was stored.
Future<RecipeDto> saveRecipe({required RecipeDto recipe}) =>
    RustLib.instance.api.crateApiRecipeSaveRecipe(recipe: recipe);

/// The recipe in exactly `household_id`, or `None` — another household's recipe is `None`.
Future<RecipeDto?> loadRecipe({
  required String householdId,
  required String recipeId,
}) => RustLib.instance.api.crateApiRecipeLoadRecipe(
  householdId: householdId,
  recipeId: recipeId,
);

/// The household's library: active recipes only.
Future<List<RecipeSummaryDto>> listRecipes({required String householdId}) =>
    RustLib.instance.api.crateApiRecipeListRecipes(householdId: householdId);

/// Recipes the household has archived, so they can be restored.
Future<List<RecipeSummaryDto>> listArchivedRecipes({
  required String householdId,
}) => RustLib.instance.api.crateApiRecipeListArchivedRecipes(
  householdId: householdId,
);

/// "Delete" (owner decision 2026-08-28: archive, never hard-delete). `archived_on` is the
/// local civil date, supplied by Dart because Rust never reads the clock (invariant 20).
/// Idempotent; returns the recipe as stored, with `archived_at` set.
Future<RecipeDto> archiveRecipe({
  required String householdId,
  required String recipeId,
  required String archivedOn,
}) => RustLib.instance.api.crateApiRecipeArchiveRecipe(
  householdId: householdId,
  recipeId: recipeId,
  archivedOn: archivedOn,
);

/// Undoes `archive_recipe`. Idempotent; returns the recipe as stored.
Future<RecipeDto> restoreRecipe({
  required String householdId,
  required String recipeId,
}) => RustLib.instance.api.crateApiRecipeRestoreRecipe(
  householdId: householdId,
  recipeId: recipeId,
);

/// The known unit vocabulary, so the editor's dropdown has one source and cannot drift from
/// the domain (as `known_restriction_kinds` does for restrictions).
Future<List<String>> knownUnitKinds() =>
    RustLib.instance.api.crateApiRecipeKnownUnitKinds();

/// Empty `id` mints a UUID. Returns the stored item.
Future<CustomIngredientDto> addCustomIngredient({
  required CustomIngredientDto item,
}) => RustLib.instance.api.crateApiRecipeAddCustomIngredient(item: item);

Future<List<CustomIngredientDto>> listCustomIngredients({
  required String householdId,
}) => RustLib.instance.api.crateApiRecipeListCustomIngredients(
  householdId: householdId,
);

/// One line matched against one restriction: the restriction, the line and the literal term
/// that matched, so every warning is explainable as "restriction ← line ← term".
class ConflictDto {
  final RestrictionDto restriction;
  final int linePosition;
  final String lineName;
  final String term;

  const ConflictDto({
    required this.restriction,
    required this.linePosition,
    required this.lineName,
    required this.term,
  });

  @override
  int get hashCode =>
      restriction.hashCode ^
      linePosition.hashCode ^
      lineName.hashCode ^
      term.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConflictDto &&
          runtimeType == other.runtimeType &&
          restriction == other.restriction &&
          linePosition == other.linePosition &&
          lineName == other.lineName &&
          term == other.term;
}

class CustomIngredientDto {
  final String id;
  final String householdId;
  final String name;
  final String? storeCategory;

  const CustomIngredientDto({
    required this.id,
    required this.householdId,
    required this.name,
    this.storeCategory,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      householdId.hashCode ^
      name.hashCode ^
      storeCategory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomIngredientDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          householdId == other.householdId &&
          name == other.name &&
          storeCategory == other.storeCategory;
}

class IngredientLineDto {
  final String originalText;
  final String name;
  final IngredientRefDto? ingredient;
  final QuantityDto quantity;
  final UnitDto unit;
  final String? preparation;
  final bool optional;

  const IngredientLineDto({
    required this.originalText,
    required this.name,
    this.ingredient,
    required this.quantity,
    required this.unit,
    this.preparation,
    required this.optional,
  });

  @override
  int get hashCode =>
      originalText.hashCode ^
      name.hashCode ^
      ingredient.hashCode ^
      quantity.hashCode ^
      unit.hashCode ^
      preparation.hashCode ^
      optional.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IngredientLineDto &&
          runtimeType == other.runtimeType &&
          originalText == other.originalText &&
          name == other.name &&
          ingredient == other.ingredient &&
          quantity == other.quantity &&
          unit == other.unit &&
          preparation == other.preparation &&
          optional == other.optional;
}

@freezed
sealed class IngredientRefDto with _$IngredientRefDto {
  const IngredientRefDto._();

  const factory IngredientRefDto.catalog({required String id}) =
      IngredientRefDto_Catalog;
  const factory IngredientRefDto.custom({required String id}) =
      IngredientRefDto_Custom;
}

@freezed
sealed class QuantityDto with _$QuantityDto {
  const QuantityDto._();

  const factory QuantityDto.unknown() = QuantityDto_Unknown;
  const factory QuantityDto.exact({required int numer, required int denom}) =
      QuantityDto_Exact;
  const factory QuantityDto.range({
    required int minNumer,
    required int minDenom,
    required int maxNumer,
    required int maxDenom,
  }) = QuantityDto_Range;
}

class RecipeDto {
  final String id;
  final String householdId;
  final String title;
  final int? servings;

  /// Ordinary user-editable data, **not** output-only: it round-trips both ways. The five
  /// rights scalars on `provenance` are the output-only fields, alongside `archived_at` and
  /// `assessment`. `None` means no estimate was given and is never rendered as a number.
  final int? prepMinutes;
  final String instructions;
  final List<IngredientLineDto> lines;
  final RecipeProvenanceDto provenance;

  /// Output only: `save_recipe` ignores it and never changes archive state; use
  /// `archive_recipe`/`restore_recipe`. ISO civil date, `None` while in the library.
  final String? archivedAt;

  /// Output only, like `archived_at`: `None` on a request, `Some` on every read-back.
  /// `save_recipe` ignores it, so no verdict can be fabricated on the write path.
  final RestrictionAssessmentDto? assessment;

  const RecipeDto({
    required this.id,
    required this.householdId,
    required this.title,
    this.servings,
    this.prepMinutes,
    required this.instructions,
    required this.lines,
    required this.provenance,
    this.archivedAt,
    this.assessment,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      householdId.hashCode ^
      title.hashCode ^
      servings.hashCode ^
      prepMinutes.hashCode ^
      instructions.hashCode ^
      lines.hashCode ^
      provenance.hashCode ^
      archivedAt.hashCode ^
      assessment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecipeDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          householdId == other.householdId &&
          title == other.title &&
          servings == other.servings &&
          prepMinutes == other.prepMinutes &&
          instructions == other.instructions &&
          lines == other.lines &&
          provenance == other.provenance &&
          archivedAt == other.archivedAt &&
          assessment == other.assessment;
}

/// `kind` is a `ProvenanceKind` string: `authored`, `imported` or `starter`.
class RecipeProvenanceDto {
  final String kind;
  final String? sourceUrl;
  final String? sourceName;
  final String? sourceAuthor;

  /// The five rights scalars are **output only**: `save_recipe` drops them, so a Dart caller
  /// cannot forge a rights basis onto a recipe. They are flat `Option<String>` rather than a
  /// nested struct for the same reason `RestrictionDto::Known` carries a token string.
  /// `rights_basis` is one of `original`, `us_federal_public_domain`, `cc0`.
  final String? rightsBasis;
  final String? attribution;
  final String? modifications;

  /// ISO civil date.
  final String? verifiedOn;
  final String? starterSlug;

  const RecipeProvenanceDto({
    required this.kind,
    this.sourceUrl,
    this.sourceName,
    this.sourceAuthor,
    this.rightsBasis,
    this.attribution,
    this.modifications,
    this.verifiedOn,
    this.starterSlug,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      sourceUrl.hashCode ^
      sourceName.hashCode ^
      sourceAuthor.hashCode ^
      rightsBasis.hashCode ^
      attribution.hashCode ^
      modifications.hashCode ^
      verifiedOn.hashCode ^
      starterSlug.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecipeProvenanceDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          sourceUrl == other.sourceUrl &&
          sourceName == other.sourceName &&
          sourceAuthor == other.sourceAuthor &&
          rightsBasis == other.rightsBasis &&
          attribution == other.attribution &&
          modifications == other.modifications &&
          verifiedOn == other.verifiedOn &&
          starterSlug == other.starterSlug;
}

class RecipeSummaryDto {
  final String id;
  final String title;
  final RestrictionAssessmentDto assessment;

  const RecipeSummaryDto({
    required this.id,
    required this.title,
    required this.assessment,
  });

  @override
  int get hashCode => id.hashCode ^ title.hashCode ^ assessment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecipeSummaryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          assessment == other.assessment;
}

/// Output only, derived at read time from the household's stored restriction set; never
/// part of a save request. Counts and lists only — no field reads as "safe".
class RestrictionAssessmentDto {
  final int ruleVersion;
  final int restrictionsChecked;
  final int linesChecked;
  final List<ConflictDto> conflicts;

  /// `Other` restrictions, matched by their own wording only.
  final List<String> wordingOnly;

  const RestrictionAssessmentDto({
    required this.ruleVersion,
    required this.restrictionsChecked,
    required this.linesChecked,
    required this.conflicts,
    required this.wordingOnly,
  });

  @override
  int get hashCode =>
      ruleVersion.hashCode ^
      restrictionsChecked.hashCode ^
      linesChecked.hashCode ^
      conflicts.hashCode ^
      wordingOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RestrictionAssessmentDto &&
          runtimeType == other.runtimeType &&
          ruleVersion == other.ruleVersion &&
          restrictionsChecked == other.restrictionsChecked &&
          linesChecked == other.linesChecked &&
          conflicts == other.conflicts &&
          wordingOnly == other.wordingOnly;
}

@freezed
sealed class UnitDto with _$UnitDto {
  const UnitDto._();

  const factory UnitDto.none() = UnitDto_None;
  const factory UnitDto.known({required String unit}) = UnitDto_Known;
  const factory UnitDto.other({required String text}) = UnitDto_Other;
}
