// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'recipe.dart';
import 'restrictions.dart';

// These functions are ignored because they are not marked as `pub`: `draft_dto`, `import_with`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

/// Fetches `url` and returns its drafts plus any recipe already saved from it. Runs the
/// network part without the database lock, then takes the lock once for the lookup.
Future<ImportResultDto> importRecipeFromUrl({
  required String householdId,
  required String url,
}) => RustLib.instance.api.crateApiRecipeImportImportRecipeFromUrl(
  householdId: householdId,
  url: url,
);

/// A recipe this household already saved from the same link.
class ExistingRecipeDto {
  final String id;
  final bool archived;

  const ExistingRecipeDto({required this.id, required this.archived});

  @override
  int get hashCode => id.hashCode ^ archived.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExistingRecipeDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          archived == other.archived;
}

/// One reviewable recipe. `recipe.id` is empty, so saving it creates a new recipe.
class ImportDraftDto {
  final RecipeDto recipe;

  /// The one consolidated "couldn't add N parts" notice, or `None`.
  final String? notice;

  /// Indexes into `recipe.lines` that name a sub-recipe already listed inline.
  final Uint32List inlineLines;

  const ImportDraftDto({
    required this.recipe,
    this.notice,
    required this.inlineLines,
  });

  @override
  int get hashCode => recipe.hashCode ^ notice.hashCode ^ inlineLines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportDraftDto &&
          runtimeType == other.runtimeType &&
          recipe == other.recipe &&
          notice == other.notice &&
          inlineLines == other.inlineLines;
}

class ImportResultDto {
  /// One per Recipe on the page; more than one means the user picks.
  final List<ImportDraftDto> drafts;
  final ExistingRecipeDto? existing;

  const ImportResultDto({required this.drafts, this.existing});

  @override
  int get hashCode => drafts.hashCode ^ existing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportResultDto &&
          runtimeType == other.runtimeType &&
          drafts == other.drafts &&
          existing == other.existing;
}
