// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'restrictions.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_domain`, `load_in`, `save_in`, `to_domain`, `to_dtos`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// The known vocabulary, so the UI's checkbox list has one source and cannot drift from the
/// domain.
Future<List<String>> knownRestrictionKinds() =>
    RustLib.instance.api.crateApiRestrictionsKnownRestrictionKinds();

Future<List<RestrictionDto>> loadRestrictions({required String householdId}) =>
    RustLib.instance.api.crateApiRestrictionsLoadRestrictions(
      householdId: householdId,
    );

/// Replaces the household's whole restriction set and returns what was stored — trimmed and
/// de-duplicated — mirroring `save_planning_cycle`'s return-what-was-stored contract, so the
/// UI shows persisted truth rather than typed input. An empty list is legal and clears the set.
Future<List<RestrictionDto>> saveRestrictions({
  required String householdId,
  required List<RestrictionDto> restrictions,
}) => RustLib.instance.api.crateApiRestrictionsSaveRestrictions(
  householdId: householdId,
  restrictions: restrictions,
);

@freezed
sealed class RestrictionDto with _$RestrictionDto {
  const RestrictionDto._();

  const factory RestrictionDto.known({required String kind}) =
      RestrictionDto_Known;
  const factory RestrictionDto.other({required String text}) =
      RestrictionDto_Other;
}
