// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'planned_meals.dart';
import 'planning.dart';
import 'recipe.dart';

// These functions are ignored because they are not marked as `pub`: `contribution_from_domain`, `derive_in`, `from_domain`, `group_from_domain`, `line_from_domain`, `reason_from_domain`, `status_from_domain`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Derives (never stores) the pantry-aware shopping projection for `from_date..=to_date`.
/// Dates are caller-supplied civil dates: Rust never reads the clock (invariant 20).
Future<ShoppingListDto> deriveShoppingList({
  required String householdId,
  required String fromDate,
  required String toDate,
}) => RustLib.instance.api.crateApiShoppingDeriveShoppingList(
  householdId: householdId,
  fromDate: fromDate,
  toDate: toDate,
);

/// One recipe line × one component's scale. `scale` reuses `ScaleDto` so it crosses as an
/// integer pair rather than an opaque handle; `None` is 1×.
class ContributionDto {
  final String plannedMealId;

  /// ISO civil date.
  final String date;
  final MealSlotDto slot;
  final int componentPosition;
  final String recipeId;
  final String recipeTitle;
  final int linePosition;
  final String originalText;
  final ScaleDto? scale;

  const ContributionDto({
    required this.plannedMealId,
    required this.date,
    required this.slot,
    required this.componentPosition,
    required this.recipeId,
    required this.recipeTitle,
    required this.linePosition,
    required this.originalText,
    this.scale,
  });

  @override
  int get hashCode =>
      plannedMealId.hashCode ^
      date.hashCode ^
      slot.hashCode ^
      componentPosition.hashCode ^
      recipeId.hashCode ^
      recipeTitle.hashCode ^
      linePosition.hashCode ^
      originalText.hashCode ^
      scale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContributionDto &&
          runtimeType == other.runtimeType &&
          plannedMealId == other.plannedMealId &&
          date == other.date &&
          slot == other.slot &&
          componentPosition == other.componentPosition &&
          recipeId == other.recipeId &&
          recipeTitle == other.recipeTitle &&
          linePosition == other.linePosition &&
          originalText == other.originalText &&
          scale == other.scale;
}

/// Mirrors `food_domain::SeparateReason`; see its doc for when each applies.
enum SeparateReasonDto {
  unresolved,
  unitNotCombinable,
  unknownQuantity,
  arithmeticOverflow,
}

/// `category` is the raw store category; `None` is "uncategorised" and comes last.
class ShoppingGroupDto {
  final String? category;
  final List<ShoppingLineDto> lines;

  const ShoppingGroupDto({this.category, required this.lines});

  @override
  int get hashCode => category.hashCode ^ lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShoppingGroupDto &&
          runtimeType == other.runtimeType &&
          category == other.category &&
          lines == other.lines;
}

/// `key` is stable across regenerations of the same snapshot: `m:…` for a merged group,
/// `s:…` for a per-contribution line. MVP-016 keys its edits on it.
class ShoppingLineDto {
  final String key;
  final String name;
  final IngredientRefDto? ingredient;
  final QuantityDto quantity;
  final UnitDto unit;
  final bool optional;
  final ShoppingLineStatusDto status;
  final SeparateReasonDto? separateReason;
  final List<ContributionDto> contributions;

  const ShoppingLineDto({
    required this.key,
    required this.name,
    this.ingredient,
    required this.quantity,
    required this.unit,
    required this.optional,
    required this.status,
    this.separateReason,
    required this.contributions,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      name.hashCode ^
      ingredient.hashCode ^
      quantity.hashCode ^
      unit.hashCode ^
      optional.hashCode ^
      status.hashCode ^
      separateReason.hashCode ^
      contributions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShoppingLineDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          name == other.name &&
          ingredient == other.ingredient &&
          quantity == other.quantity &&
          unit == other.unit &&
          optional == other.optional &&
          status == other.status &&
          separateReason == other.separateReason &&
          contributions == other.contributions;
}

/// `OmittedPantryMarked` lines are still returned in full so the UI can offer restore; a
/// pantry mark suppresses a purchase but never proves quantity (invariant 6).
enum ShoppingLineStatusDto { needed, omittedPantryMarked }

class ShoppingListDto {
  final int algorithmVersion;
  final String fromDate;
  final String toDate;
  final List<ShoppingGroupDto> groups;
  final int nonRecipeComponents;
  final int contributionCount;

  const ShoppingListDto({
    required this.algorithmVersion,
    required this.fromDate,
    required this.toDate,
    required this.groups,
    required this.nonRecipeComponents,
    required this.contributionCount,
  });

  @override
  int get hashCode =>
      algorithmVersion.hashCode ^
      fromDate.hashCode ^
      toDate.hashCode ^
      groups.hashCode ^
      nonRecipeComponents.hashCode ^
      contributionCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShoppingListDto &&
          runtimeType == other.runtimeType &&
          algorithmVersion == other.algorithmVersion &&
          fromDate == other.fromDate &&
          toDate == other.toDate &&
          groups == other.groups &&
          nonRecipeComponents == other.nonRecipeComponents &&
          contributionCount == other.contributionCount;
}
