// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `starter_error`, `to_recipes`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Seeds the global ingredient catalog and any cook-reviewed starter recipe this household
/// does not already hold. Idempotent and cheap to re-run: once every catalog id and slug is
/// present it writes no rows, so it is safe to call on every app start.
Future<StarterInstallReportDto> installStarterContent({
  required String householdId,
}) => RustLib.instance.api.crateApiStarterInstallStarterContent(
  householdId: householdId,
);

/// What one install call did. `available` and `pending_cook_review` exist so `installed: 0`
/// reads as *empty by design* — nothing has a recorded cook review yet — rather than as a
/// swallowed failure.
class StarterInstallReportDto {
  final int installed;
  final int skipped;
  final int catalogInstalled;

  /// Shipped-set size: entries carrying a recorded cook review.
  final int available;

  /// Authored but not yet cooked. These never install (MVP-011 AC-3).
  final int pendingCookReview;

  const StarterInstallReportDto({
    required this.installed,
    required this.skipped,
    required this.catalogInstalled,
    required this.available,
    required this.pendingCookReview,
  });

  @override
  int get hashCode =>
      installed.hashCode ^
      skipped.hashCode ^
      catalogInstalled.hashCode ^
      available.hashCode ^
      pendingCookReview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StarterInstallReportDto &&
          runtimeType == other.runtimeType &&
          installed == other.installed &&
          skipped == other.skipped &&
          catalogInstalled == other.catalogInstalled &&
          available == other.available &&
          pendingCookReview == other.pendingCookReview;
}
